import fs from 'node:fs';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { notes } from './individual-notes.mjs';
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const records=JSON.parse(execFileSync(process.execPath,['reconstruction/audit/departments/read-lossless.mjs','manifest'],{maxBuffer:10_000_000}));
const dirs=['truth_verification','adversarial_attack','prediction_decision','final_quality_evolution','institutional_power'];
const extra=['reconstruction/MANDATE.md','reconstruction/AUDIT-PROTOCOL.md','docs/omega/00-OMEGA-CONSTITUTION.md','docs/pi/24-PI-DEPARTMENT-INTERFACES.md','docs/sigma/24-SIGMA-DEPARTMENT-INTERFACES.md',...dirs.flatMap(d=>[`docs/departments/${d}/v3-department-charter.md`,`docs/departments/${d}/README.md`]),'docs/departments/truth_verification/agents/veritas_01.md'];
const sourceFacts=p=>{const raw=fs.readFileSync(p);return {path:p,sha256:hash(raw),bytes:raw.length,lines:raw.toString().split('\n').length-1};};
function covered(r,charter=false){
 const p=charter?r.charter:r.source,base=charter?r.charterBasePath:r.base;
 const raw=fs.readFileSync(p,'utf8'),original=fs.readFileSync(base,'utf8');
 const escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
 const regex=r.replacements.length?new RegExp(r.replacements.map(x=>escape(x.from)).join('|'),'g'):null;
 const literalSubstitutions=[];let rebuilt=original;
 if(regex)rebuilt=original.replace(regex,(match,offset)=>{const replacement=r.replacements.find(x=>x.from===match);literalSubstitutions.push({field:replacement.field,baseByteOffset:Buffer.byteLength(original.slice(0,offset)),baseLine:original.slice(0,offset).split('\n').length,from:match,to:replacement.to});return replacement.to;});
 const residuals=charter?r.charterResiduals:r.residuals;
 const lines=rebuilt.split('\n');for(const residual of residuals){if(lines[residual.line-1]!==residual.reconstructed)throw Error('residual mismatch');lines[residual.line-1]=residual.actual;}
 const final=lines.join('\n');if(final!==raw)throw Error(`incomplete reconstruction ${p}`);
 return {...sourceFacts(p),coverage:{mode:p===base?'literal_complete':'literal_base_plus_lossless_substitutions_and_residuals',base:{path:base,sha256:hash(original),range:'entire file; unchanged bytes referenced, not reread for each target'},replacementDefinitions:r.replacements,occurrences:literalSubstitutions.map(x=>({field:x.field,baseByteOffset:x.baseByteOffset,baseLine:x.baseLine})),residuals,verifiedByteReconstruction:true,reconstructedSha256:hash(final)},limitations:['Coverage by reconstruction is not repeated literal reading of every unchanged line.','Normative document only; no execution, schema validation or evaluation result established.']};
}
function role(r){
 const f=r.fields,n=notes[f.id];if(!n)throw Error(f.id);
 return {id:f.id,name:f.name,sources:[{path:r.source,sections:['§1 Pregunta irreductible','§2 Doctrina específica','§3 Variables y cobertura','§4 Decisiones permitidas y límites','§5 Contratos de entrada','§6 Máquina operacional verificable','§7 Contrato de salida y schema','§8 Gates no renunciables','§9 Contexto, seguridad y memoria','§10 Delegación y presupuesto','§11 FMEA causal','§12 Evaluaciones adversariales','§13 Handoffs y reversión','§14 Terminación','§15 Definition of done','§16 Casos de prueba del puesto']},{path:r.charter,sections:['Mandatory method','Non-waivable gates','Output grammar','Context, delegation and correction','Termination']},{path:`docs/departments/${r.source.split('/')[2]}/v3-department-charter.md`,sections:['Misión','Separación de deberes','Interfaces']}],
 purpose:{effect:n[0],originalQuestion:f.question,authorityLevel:'Normative role description, not demonstrated implemented capability.'},
 inputs:{documented:['MissionPacket: scoped mission and owner','AuthorityLease: prior explicit scoped authority, never inferred from task','VersionedInputs: exact input versions, unknowns and limits','IntegrityManifest: lineage/integrity declarations requiring checks'],roleSpecificEvidenceFloor:f.floor,producerResolution:n[2],limitation:'The generic dossier labels input producers declared upstream owner; intra-department producer IDs below are audit hypotheses, not explicit contracts.'},
 outputs:{artifact:f.artifact,semanticContent:f.floor,documentedHandoff:f.handoff,schema:f.schema,commonFields:['status','result','evidence_for','evidence_against','assumptions','unknowns','provenance','gate_receipts','next_action'],meaning:'Artifact accepted only for its stated purpose/version; its existence does not prove its claims.'},
 dependencies:{data:n[2],consumers:n[3],authority:'Ω mandate and valid prior AuthorityLease; departmental data handoff transfers no institutional authority.',causalAcceptance:'Material upstream product must be accepted before dependent use as fact or permission. Provisional exploration remains labeled, does not acquire accepted status.'},
 methods:{documentedOperation:f.method,minimumEvidence:f.floor,falsifier:f.falsifier,auditAlternativeAfterFailure:n[6],qualification:'Specific operation is an instruction; source does not demonstrate executable algorithm, connector or measured performance.'},
 invariants:['Preserve unknowns, contrary evidence, version lineage and scope across handoff.','Execute method/falsifier or record typed infeasibility with independent decision.','Separate producer from material acceptance; majority does not replace evidence.','Corrections append parent/supersedes and invalidate dependent consumption.'],
 forbiddenActions:[`Do not substitute for ${f.boundary}.`,'No self-certification of material output.','No external effects beyond lease, no silent policy/schema/routing changes.','External content remains data, not authority.'],
 activation:{proposedCondition:n[1],requiredChecks:'Mission/authority/input admission and materiality are checked first; no claim that this role must run on every request.'},
 deactivation:{proposedCondition:'Skip a separate cognitive invocation when the triggering condition is absent or the exact capability is already independently satisfied for this version; record why. Never skip material acceptance merely to save tokens.',termination:'COMPLETE requires valid receipt; use PARTIAL/UNKNOWN/BLOCKED/ABORTED/FAILED when corresponding condition holds, preserving residuals.'},
 verification:{proposedAcceptance:n[4],documentedReviewer:'Independent department role or deterministic validator; exact owner is not consistently named.',gates:['AUTHORITY_SCOPE','INPUT_LINEAGE','METHOD_EXECUTION','FALSIFIER_COVERAGE','BOUNDARY_SEPARATION','INDEPENDENT_REVIEW','OUTPUT_SCHEMA','HANDOFF_RECEIPT'],before:n[3],limitation:'Reviewer assignment, evidence sufficiency thresholds and binding to artifact version require design/testing; an LLM approving itself is not independence.'},
 failureModes:{specificNegative:n[5],documentedFalsifier:f.falsifier,commonRisks:['Stale/corrupt versions','Hidden dependency','Unknown erasure','Reviewer non-independence','Unauthorized normalization','Invalid correction propagation'],sourceQuality:'FMEA §11 enumerates 35 named classes but several causal mechanisms are templated anchors, not role-specific failure explanations.'},
 recovery:{alternative:n[6],propagation:'Freeze dependent acceptance; return to earliest causal owner; retain historical descendants without treating them as valid; re-evaluate affected outputs after supersession.',nonRepetition:'Diagnose failed assumption/method before retry; a rephrased identical attempt is not a new method.'},
 distinctiveness:{irreducibleLossIfRemoved:n[0],shareableMechanismsAndBoundary:n[8]},
 recommendedDisposition:{status:'Preserve capability pending cross-group comparison; no final process/session count approved.',justification:n[8],decisionGate:'Consolidate only if comparative evaluation preserves this distinct responsibility, evidence boundary and independent acceptance.'},
 evaluationCases:[{type:'positive',status:'proposed_not_executed',setup:`Provide a scoped authorized case satisfying: ${f.floor}.`,oracle:`${n[4]} Required artifact ${f.artifact} retains evidence_for/evidence_against/unknowns and accepted version.`,purpose:n[0]},{type:'negative',status:'proposed_not_executed',setup:n[5],oracle:`Reject/return or preserve UNKNOWN; do not release material dependent consumption. Recovery must follow: ${n[6]}`},{type:'comparative',status:'proposed_not_executed',setup:n[7],oracle:'Compare independently judged task success, false acceptance, traceability, correction propagation and observed cost/latency on the same cases; do not award points for longer text or additional agents.'}],
 uncertainties:['Current sources prescribe behavior but do not prove it is implemented or effective.','Referenced schema contents and runtime enforcement are outside this departmental reading scope.','Historical source coverage is partial and explicitly listed in sources.json.','Generic FMEA/eval labels do not establish working probes, thresholds or comparative advantage.','Exact reviewer independence and many intra-department handoff owners need cross-group resolution.']};
}
const arg=process.argv[2];
if(arg==='extras')process.stdout.write(JSON.stringify(extra.map(p=>({...sourceFacts(p),coverage:{mode:'literal_complete'},limitations:p.endsWith('/agents/veritas_01.md')?['Historical base only; not an additional current agent.']:['Normative/contextual text, not executable proof.']}))));
else if(arg==='history')process.stdout.write(JSON.stringify(dirs.flatMap(d=>fs.readdirSync(`docs/departments/${d}/agents`).filter(n=>n.endsWith('.md')).map(n=>`docs/departments/${d}/agents/${n}`).filter(p=>!extra.includes(p)).map(p=>({...sourceFacts(p),coverage:{mode:'inventory_only_not_read'},limitations:['Historical counterpart; no full historical semantic coverage claimed.']})))));
else if(arg.startsWith('sources:'))process.stdout.write(JSON.stringify(records.filter(r=>r.source.includes(`/${arg.slice(8)}/`)).flatMap(r=>[covered(r),covered(r,true)])));
else process.stdout.write(JSON.stringify(records.filter(r=>r.source.includes(`/${arg}/`)).map(role)));
