// Audit artifact assembly only; does not implement or activate agents.
import fs from 'node:fs';
import crypto from 'node:crypto';
const read=p=>fs.readFileSync(p,'utf8');
const root='/home/cardeex/openclaw-workspace/sovereign-os/reconstruction/audit/pi/';
const rolesPath=root+'roles.json',sourcesPath=root+'sources.json';
const roles=JSON.parse(read(rolesPath)),sources=JSON.parse(read(sourcesPath));
const originalIds=new Set(roles.roles.map(r=>r.id));
const notes=JSON.parse(read(root+process.argv[2]));
for(const [num,n] of Object.entries(notes)){
 const manifest=root+`coverage-pi${num}.json`,r=JSON.parse(read(manifest)),f=r.fields;
 const role={id:f.id,name:f.name,sources:[{path:r.source,sections:['Necesidad y unidad irreductible','Contratos de input · 6','Fronteras explícitas','Workflow específico · 9','Gates medibles · 8','FMEA causal · 29','Evaluaciones adversariales · 16','Conflicto constitutivo']},{path:r.charter,sections:['1–14']},{path:'docs/pi/06-PI-COUNCIL-OPERATING-SYSTEM.md',sections:['2–4']}],purpose:n.purpose,
 inputs:[{artifact:'OmegaStrategyMandate / IntelligenceHandoff / ResourceEnvelope',required:true,semanticCondition:'Contrato común: identidad, autoridad, vigencia y procedencia; schema-valid no equivale a aceptación semántica.'},{artifact:'AuthorityDetermination / ConstraintRegister / OutcomeFeedback',required:'Optional documental; condición material puede hacer imprescindible autoridad/evidencia',semanticCondition:n.neededData}],
 outputs:[{artifact:f.artifact,semanticCondition:n.deactivation},{artifact:f.ledger,semanticCondition:'Historia append-only, snapshot y supersedes, no permiso de ejecutar ni verdad por mera persistencia.'}],
 dependencies:{dataProducers:n.neededData,consumers:n.consumers,authority:'Π01 admite encargo; Ω17 custodia StrategyPortfolio; Ω01/humano decide; Ω20 asigna recursos; Ω21/Legal conserva autorización jurídica. Interfaces no delegan estas potestades.'},methods:[...f.methods,{alternative:n.recovery}],
 invariants:['Conservar fuente, incertidumbre, disenso, owner y reversión','Gates sobre snapshot inmutable; productor no se autoacepta','Preferencia estratégica no equivale a afirmación factual validada ni decisión soberana'],forbiddenActions:['Reescribir realidad de Σ para favorecer tesis','Asignar capital, contratar, comprar o desplegar por recomendación Π','Borrar objeciones protegidas de Π38/39','Consumir evidencia rechazada como conocimiento aceptado'],activation:n.activation,deactivation:n.deactivation,
 verification:{beforeConsumer:true,acceptance:n.acceptance,gaps:'Workflow común admite schema-valid/not-stale en M2–M9; hace falta especificar aceptación semántica de materialidad, no inferirla por nombre del gate.'},failureModes:[n.failure,'FMEA plantilla rota causas y gates: no demuestra diagnóstico específico de tool_failure/prompt_injection'],recovery:[n.recovery,'Cualquier nueva fuente material requiere nueva revisión; invalidar transitivamente premisas afectadas, no toda la cartera indiscriminadamente.'],distinctiveness:n.distinctiveness,
 recommendedDisposition:{status:'CONSERVAR_CAPACIDAD_EVALUAR_EJECUCION_COMPARTIDA',rationale:n.distinctiveness,architecturalDecision:false},evaluationCases:[{type:'positive',case:n.positive,expected:'Cumplir el efecto específico y condiciones de aceptación descritas; prueba propuesta no ejecutada.'},{type:'negative',case:n.negative,expected:'Detectar el defecto y retornar/escalar sin fabricar certeza o autorización.'},{type:'comparison',case:n.comparison,expected:'Medir si retirar esta operación cambia la detección del error; no confundir papel documental con contribución empírica.'}],uncertainties:[n.uncertainty,'Dossier declarativo S2; oráculos nominales y métodos enumerados no demuestran ejecución.','Comparación interdepartamental final pendiente de dirección.']};
 const i=roles.roles.findIndex(x=>x.id===f.id);if(i<0)roles.roles.push(role);else roles.roles[i]=role;
 for(const path of [r.source,r.charter]){const s=sources.sources.find(x=>x.path===path);s.coverage={status:'READ_COMPLETE',ranges:[[1,s.lines]],method:'full_base_01_read_plus_observed_literal_replacements_and_every_residual_read; exact dossier and charter reconstruction',duplicateReferences:[{manifest,sha256:crypto.createHash('sha256').update(read(manifest)).digest('hex'),base:path===r.source?r.base:r.charterBase,locator:'operations/charterOperations and replacements with original code-unit offset and line; same mappings exact; source hashes in manifest'}]};s.limitations=['Current v3 text only; mechanical equality validates coverage, not system behavior.'];}
}
roles.roles.sort((a,b)=>a.id.localeCompare(b.id));
roles.unresolved[0]=`Lectura/fichas completas ${roles.roles.map(r=>r.id).join(', ')}; restantes pendientes. No cierre de auditoría.`;
for(const [path,value] of [[rolesPath,roles],[sourcesPath,sources]]){if(process.argv[3]&&!path.endsWith(process.argv[3]))continue;const old=read(path).trimEnd(),next=JSON.stringify(value,null,2);if(path===rolesPath){const additions=roles.roles.filter(r=>!originalIds.has(r.id));if(!additions.length)continue;const insert=additions.map(r=>JSON.stringify(r,null,2).split('\n').map(l=>'    '+l).join('\n')).join(',\n')+',';console.log('*** Begin Patch\n*** Update File: '+path+'\n@@\n   "roles": [\n'+insert.split('\n').map(l=>'+'+l).join('\n')+'\n*** End Patch');continue;}console.log('*** Begin Patch\n*** Update File: '+path+'\n@@\n'+old.split('\n').map(x=>'-'+x).join('\n')+'\n'+next.split('\n').map(x=>'+'+x).join('\n')+'\n*** End Patch');}
