import fs from 'node:fs';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {notes} from './individual-notes.mjs';
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const ids=Array.from({length:21},(_,i)=>i+20);
const section=(text,n)=>text.match(new RegExp(`^## ${n}\\. [^\\n]+\\n([\\s\\S]*?)(?=^## |$(?![\\s\\S]))`,'m'))?.[1]?.trim()||'';
const subsection=(text,name)=>text.split('### '+name+'\n')[1]?.split('\n### ')[0]?.trim()||'';
const blocks=text=>text.split(/^### /m).slice(1).map(b=>({heading:b.split('\n')[0],text:b.slice(b.indexOf('\n')+1).trim()}));
const facts=p=>{const b=fs.readFileSync(p);return {path:p,sha256:hash(b),bytes:b.length,lines:b.toString().split('\n').length-1};};
const roles=ids.map(i=>{
 const path=`docs/sigma/agents/v3/sigma-${i}-dossier.md`,charter=`config/sigma/v3/charters/sigma-${i}.system.md`,text=fs.readFileSync(path,'utf8'),n=notes[i];
 if(!n)throw Error('missing analysis '+i);
 const doctrine=section(text,4),annex=section(text,18);
 return {id:`sigma_${i}`,name:text.split('\n')[0].replace(/^# Σ\d+ — /,'').replace(' · Agent Dossier v3',''),sources:[{path,sections:[...text.matchAll(/^## (.+)$/gm)].map(x=>x[1])},{path:charter,sections:['entire file']},{path:'docs/sigma/00-SIGMA-CONSTITUTION.md',sections:['entire file']},{path:'docs/sigma/01-SIGMA-SYSTEM-ARCHITECTURE.md',sections:['entire file']}],
 purpose:{effect:n.effect,documented:section(text,1),authorityLevel:'Normative current dossier, not demonstrated running capability'},
 inputs:{contracts:blocks(section(text,5)),acceptance:'Schema/hash/producer/authority/freshness checks admit inputs but do not establish factual entailment. Material upstream products need accepted version and semantic scope before dependent use.'},
 outputs:{contract:section(text,7),stateAndUnknown:subsection(annex,'Output y UNKNOWN'),semanticEffect:n.effect,qualification:'Existence or schema validity does not certify content; preserve provisional/UNKNOWN status.'},
 dependencies:{documentedBoundaries:section(text,3),institutional:'Ω mandates and scoped leases precede work; data handoff confers no authority. Σ operational intelligence remains a candidate input to Ω sovereign acceptance.',causalOrder:n.acceptance},
 methods:{documented:subsection(doctrine,'Procedimiento'),stateMachine:section(text,6),alternativeOnFailure:n.alternative},
 invariants:{variables:subsection(doctrine,'Variables obligatorias'),epistemicContext:section(text,8),safety:section(text,13),materialAcceptance:'Internal schema-valid method transition is not independent acceptance. A material output must be accepted before its dependent consumer treats it as established.'},
 forbiddenActions:{roleShortcuts:subsection(doctrine,'Atajos prohibidos'),authorityMatrix:section(text,10),boundaries:section(text,3)},
 activation:{documented:subsection(annex,'Activación contextual'),interpretation:'Activate only relevant triggered capability with prior authority/input floor; no fixed session count or universal invocation assumed.'},
 deactivation:{stops:subsection(doctrine,'Stop conditions'),budgetTermination:section(text,14),lifecycle:subsection(annex,'Ciclo de vida y estados de control'),interpretation:'A persistent watch may retain a future trigger while a finite episode terminates. Typed incomplete states are not COMPLETE.'},
 verification:{gates:blocks(section(text,11)),acceptance:n.acceptance,selfCheckLimit:section(text,17),requiredBeforeUse:'Bind decision to exact artifact version, evidence and genuinely independent reviewer; do not rely on department label or multiple nominal agents.'},
 failureModes:{falsifiers:subsection(doctrine,'Falsificadores/condiciones de retorno'),fmea:blocks(section(text,12)),negativeProbe:n.negative,qualityOfSpecification:'FMEA rotates variables/methods/falsifiers; names and repeated causal anchors are not proof that detection matches the named fault. Proposed probes need concrete independent oracles.'},
 recovery:{alternative:n.alternative,documented:subsection(annex,'Memoria, corrección e idempotencia'),propagation:'Freeze affected descendants; notify prior consumers; recompute through original owners from earliest invalid root; new version and independent reacceptance, no rhetorical patch or silent overwrite.'},
 distinctiveness:{loss:n.effect,shareable:n.share,specialists:blocks(section(text,9)),interpretation:'Logical capability, session and authority owner are distinct; common machinery does not justify merging producer with acceptance.'},
 recommendedDisposition:{status:'Preserve capability pending whole-system comparison; execution consolidation not yet approved',justification:n.share,condition:'Comparative ablation must retain semantic responsibility, least authority and independent material acceptance.'},
 evaluationCases:[{type:'positive',status:'proposed_not_executed',setup:n.positive,oracle:n.acceptance},{type:'negative',status:'proposed_not_executed',setup:n.negative,oracle:'Detect causal defect, reject material promotion and perform scoped recovery: '+n.alternative},{type:'comparative',status:'proposed_not_executed',setup:n.comparison,oracle:'Same frozen cases, independent labels, observed false acceptance/omission/cost/latency. More words, agents or checkboxes earn no credit.'}],
 uncertainties:[...n.issues,'No executable schema contents, runtime enforcement or evaluation performance certified by this textual audit.','Historical counterparts and machine JSON full semantic coverage not claimed; see sources manifest.','Normative context/provider/model tier choices are not measured best routing.'],documentedIllustrations:section(text,16)};
});
if(process.argv[2]==='roles')process.stdout.write(JSON.stringify({group:'sigma-complement',status:'current_charters_and_dossiers_20_40_audited_history_partial',roles,unresolved:roles.flatMap(r=>r.uncertainties.slice(0,-3).map(issue=>({id:r.id,issue})))}));
else if(process.argv[2]==='role')process.stdout.write(JSON.stringify(roles.find(r=>r.id===`sigma_${process.argv[3]}`)));
else {
 const sources=ids.flatMap(i=>JSON.parse(execFileSync(process.execPath,['reconstruction/audit/sigma-complement/read-lossless.mjs',String(i),'manifest'],{maxBuffer:20_000_000}))).map(r=>({...facts(r.source),coverage:{mode:r.source===r.base?'literal_complete':'literal_base_plus_lossless_exact_substitutions_and_residuals',base:{path:r.base,sha256:r.baseSha256,scope:'entire base read literally; byte-identical lines referenced rather than repeatedly read'},replacementDefinitions:r.definitions,occurrences:r.occurrences,residuals:r.residuals,equalLines:r.equalLines,verifiedByteReconstruction:r.verifiedByteReconstruction},limitations:['Coverage by exact reconstruction is not repeated literal reading. All replacement strings/positions and residual target lines read; truncated residuals reread.','Normative text, no implemented capability proof.']}));
 const extras=['reconstruction/MANDATE.md','reconstruction/AUDIT-PROTOCOL.md','docs/sigma/00-SIGMA-CONSTITUTION.md','docs/sigma/01-SIGMA-SYSTEM-ARCHITECTURE.md','docs/sigma/24-SIGMA-DEPARTMENT-INTERFACES.md','docs/omega/00-OMEGA-CONSTITUTION.md','docs/pi/24-PI-DEPARTMENT-INTERFACES.md'];
 sources.push(...extras.map(p=>({...facts(p),coverage:{mode:'literal_complete'},limitations:['Contextual/normative source, not execution evidence.']})));
 for(const i of ids){for(const p of [`config/sigma/v3/dossiers/sigma-${i}.json`,`docs/sigma/agents/sigma-${i}.md`])if(fs.existsSync(p))sources.push({...facts(p),coverage:{mode:p.endsWith('.json')?'machine_candidate_fields_used_not_full_semantic_read':'historical_inventory_only_not_read'},limitations:['Not included in current charter/dossier semantic coverage. Historical differences remain pending; no equivalence claimed.']});}
 process.stdout.write(JSON.stringify({group:'sigma-complement',status:'current_20_40_complete_historical_partial',method:'Full sigma20 base plus exact literal substitutions with all positions and complete residual lines; byte reconstruction verified independently per source. Candidate spelling derivation never normalizes equality.',sources,limitations:['Σ01–19 handled by separate audit/sigma owner.','Machine-readable JSON used to discover raw replacement candidates only; complete JSON not claimed read.','Historical counterpart comparison pending.','No tests of production behavior executed.']}));
}
