import{spec as s,boundary as b,scenario as c}from"./spec-helper.mjs";
export default {
sigma_11:s(
"¿Qué ocurrió o existe dónde y cuándo, dentro de qué resolución, error de geolocalización y cobertura observacional?","La observación espacio-temporal y su footprint; no la identidad, causalidad o intención del actor.",
["Definir area/time of interest","Seleccionar imagery/geospatial routes autorizadas","Normalizar coordenadas y reference frames","Estimar resolution/occlusion/error","Realizar geolocation independiente","Declarar coverage gaps y privacy limits"],
["area of interest","time window and revisit","coordinate reference system","spatial resolution","geolocation error ellipse","temporal uncertainty","cloud/occlusion","sensor provenance","change-detection baseline","privacy sensitivity"],
["Fijar AOI, temporal window y event tolerance antes de buscar","Separar acquisition time, scene time, processing time y observation time","Normalizar CRS/datums conservando raw coordinates","Modelar ground sample distance, parallax, occlusion y seasonal baseline","Comparar cambios contra imagery comparable, no visualmente conveniente","Obtener geolocation por landmarks/telemetry en ruta independiente","Cuantificar coverage y non-observation probability","Preservar pixels/tiles y transformation chain","Redactar/localizar sólo según need-to-know"],
["Error ellipse permite múltiples sitios candidatos","Imágenes no son comparables por estación/ángulo/resolución","Timestamp no corresponde al fenómeno","Cloud/occlusion hace ausencia no diagnóstica","Geolocation depende del mismo metadata cuestionado","Privacy surface excede propósito autorizado"],
["Afirmar ubicación exacta desde imagen borrosa","Interpretar no observado como no existente","Usar mapa reproyectado sin transformación","Ocultar mosaic/composite","Hacer identity inference desde localización sola","Publicar coordenadas sensibles"],
["GeotemporalCollectionPlan con error/coverage aceptados","Resolution ceiling obliga UNKNOWN","AOI/time window expira","Privacy/authority bloquea","Marginal revisit no cambia decision threshold"],
[
b("Σ06","diseña método geo/temporal","posee collection portfolio","GeotemporalTasking","Σ11 no reprioriza mission"),b("Σ10","posee imagery/geo observables","posee sensor/telemetry técnica","shared clock/CRS contract","no duplicar sensor authority"),b("Σ08","usa mapas/records autenticados","posee corpus documental","RecordLocator","mapa no equivale a terrain truth"),b("Σ12","reporta occlusion/revisit gaps","posee gap contingency","CollectionGapCase","no ocultar blind zones"),b("Σ14","entrega raw imagery","admite/quarantine","EvidenceIntakeDecision","no procesar payload hostil fuera sandbox"),b("Σ17","provee tile/transform lineage","posee provenance","OperationalProvenanceBundle","Σ11 no sella lineage global"),b("Σ18","entrega location candidates","resuelve entity identity","EntityResolutionCase","co-location no prueba identidad"),b("Σ19","entrega four-time metadata","reconstruye chronology","TemporalObservationPacket","scene time no fija event time"),b("Σ20","aporta spatial edges","modela network","EdgeCandidate","proximidad no prueba relación"),b("Σ21","define resolution/error","valida measurement","MeasurementAssessment","precision cartográfica no es accuracy"),b("Ω21","describe surveillance/privacy scope","autoriza uso","AuthorityDetermination","availability no concede legitimidad"),b("Σ38","entrega independent geolocation sample","audita method","QualityReport","Σ11 no autocertifica localización")],
["Metadata spoofing","CRS mismatch","Cloud/occlusion bias","Composite-image deception","Privacy leakage","Change-detection seasonality","Geolocation circularity","Timestamp conflation"],
[c("normal","Verificar expansión de planta","imagery mensual con nubes","define baseline estacional y error ellipse","INDEPENDENT_GEOLOCATION","cambio corroborado dentro de 18 m"),c("contradicción","satélite y geotag discrepan","metadata puede estar spoofed","geolocaliza por landmarks blind","COORDINATE_NORMALIZATION","metadata degradado; sitio resuelto"),c("ataque","solicitan seguir persona","purpose excede misión","bloquea por privacy/authority","PRIVACY","sin colección"),c("recuperación","mosaic mezcló dos fechas","timeline contaminado","revoca composite, reconstruye tiles y notifica","FOUR_TIME_SEPARATION","productos dependientes reabiertos")]),

sigma_12:s(
"Cuando la evidencia requerida no llega, ¿es ausencia del fenómeno, fallo de acceso, denial adversarial, incapacidad del método o un UNKNOWN irreducible?","El gap de colección como caso causal; no la conclusión sustantiva.",
["Clasificar gap y cause hypotheses","Medir detection probability","Diseñar proxies/contingencies","Escalar denial/spoofing","Declarar inaccessible/unknowable","Cerrar rutas de bajo valor"],
["required observable","expected detection probability","route failure mode","denial likelihood","proxy construct validity","decision sensitivity","time-to-window-close","alternative route independence","residual gap","cost of ignorance"],
["Separar NO_DATA, NO_ACCESS, NO_SIGNAL, METHOD_FAILURE y ADVERSARY_DENIAL","Estimar probabilidad de detección condicionada a que el fenómeno exista","Inspeccionar pipeline/access/permissions antes de inferir ausencia","Construir hipótesis de denial y benign failure","Buscar proxy con mechanism link y error explícito","Priorizar contingency por decision sensitivity×tractability","Diseñar ruta ortogonal que no revele discriminant","Declarar UNKNOWN subtype y cost of ignorance","Cerrar gap sólo por resolution, accepted residual o impossibility"],
["Detection probability es baja/desconocida","Proxy no transporta al construct","Todas las rutas comparten failure point","Adversario conoce el indicador","Access denial es jurídico y no técnico","Window cierra antes de nueva colección"],
["Ausencia de evidencia = evidencia de ausencia","Inventar proxy por conveniencia","Reintentar infinitamente la misma ruta","Ocultar failed searches","Usar método ilícito por criticidad","Declarar unknowable antes de probar accesos autorizados"],
["Gap resuelto con evidencia admisible","Residual aceptado por decision owner","UNKNOWABLE/INACCESSIBLE demostrado","VOI de contingencias no positivo","Risk/authority/time bloquea y se escala"],
[
b("Σ04","recibe gap priority","mide denominator/coverage","CriticalGapRecord","Σ12 no cambia weight"),b("Σ06","recibe failed routes","posee portfolio","CollectionFailureEvent","Σ12 no tasking global"),b("Σ07","solicita novel access","descubre routes","AccessContingency","denial no autoriza bypass"),b("Σ10/Σ11","diagnostica technical/geo failure","poseen método","FailureDiagnosticPacket","Σ12 no calibra sensor"),b("Σ16","evalúa correlation de fallos","posee source dependencies","RouteDependencyGraph","rutas múltiples pueden fallar juntas"),b("Σ21","solicita proxy validity","posee measurement","ProxyAssessment","Σ12 no certifica construct"),b("Σ29","entrega denial signals","analiza deception","DeceptionAssessment","gap no prueba adversario"),b("Σ33","declara indicator blind spot","posee warning state","WarningCoverageGap","Σ12 no suprime warning"),b("Σ34","entrega unknown surface","busca sorpresa","SurpriseGap","no convertir cualquier gap en tail"),b("Σ02","recomienda replan/stop","orquesta misión","GapDisposition","Σ12 no cancela mission"),b("Ω20","expone cost of ignorance","decide extra resource","ResourceException","gap no crea presupuesto"),b("Ω12","propone UNKNOWN subtype","gobierna lenguaje epistémico","EpistemicReview","Σ12 no suaviza imposibilidad")],
["Absence inference","Proxy substitution error","Denial paranoia","Retry loop","Gap concealment","Shared failure point","Window blindness","Illegal contingency"],
[c("normal","Falta precio neto de mercado","contratos privados","modela detection y proxy fiscal","PROXY_VALIDITY","rango parcial con gap explícito"),c("contradicción","sensor sin señal pero planta visible","pipeline o spoofing","separa failures y tasking técnico","GAP_CLASSIFICATION","no declara inactividad"),c("ataque","se exige obtener dato inaccesible","presión P1","rechaza bypass e informa cost of ignorance","UNKNOWN_HONESTY","INACCESSIBLE"),c("recuperación","gap cerrado por falsa ausencia","nueva fuente prueba existencia","reabre nodo causal y descendientes","DECISION_SENSITIVITY","estimate recalculado")]),

sigma_13:s(
"¿Cómo hacer utilizable una fuente sensible exponiendo a cada actor sólo lo indispensable y manteniendo auditoría sellada/revocación?","El plan de handling, compartimentación y protección; no la evaluación de fiabilidad ni la supresión de evidencia incómoda.",
["Clasificar sensibilidad y harm model","Crear compartments/need-to-know","Tokenizar identidad y secretos","Autorizar redaction/dissemination paths","Revocar acceso y propagar","Mantener sealed audit accessible a Ω7/Ω3"],
["source harm severity","identity exposure surface","need-to-know purpose","compartment membership","secret reference","redaction reversibility","access duration","recipient clearance","revocation latency","audit escrow integrity"],
["Modelar daño por exposición, inferencia y combinación","Separar identity, content, metadata y relationship compartments","Emitir opaque source token y resolver identidad sólo en vault","Aplicar purpose+role+mission+time policy en cada read","Minimizar context sin romper claim provenance","Generar redaction manifest con parent hash","Probar revocation y downstream recall antes de uso material","Permitir auditoría sellada independiente sin revelar al productor","Registrar toda excepción y failed access"],
["Redaction impide verificar claim material","Metadata permite reidentificación","Compartment owner es sujeto investigado","Revocation no alcanza copies downstream","Recipient purpose no coincide","Protección se usa para ocultar contrary evidence"],
["Compartir secretos dentro del prompt","Usar clasificación como sinónimo de verdad","Eliminar detalles en vez de ocultarlos","Negar acceso a inspector autorizado","Crear compartment sin owner/expiry","Prometer anonimato absoluto"],
["HandlingPlan probado y acknowledgments completos","Fuente no puede usarse sin exposure desproporcionada","Consent/authority revocado","Mission closes y retention policy ejecuta","Sealed audit transferido"],
[
b("Σ09","define handling antes de contacto","posee elicitation","SourceHandlingPlan","handler no cambia testimony"),b("Σ15","protege identity/access metadata","evalúa source","sealed SourceAssessment view","protección no eleva reliability"),b("Σ17","entrega redacted lineage refs","posee forensic chain","token→sealed locator","Σ13 no rompe lineage"),b("Σ14","define safe handling de raw input","admite/quarantine","ClassificationDecision","Σ13 no admite contenido"),b("Σ16","oculta identity pero permite dependency edges","mapea source origins","Privacy-preserving cluster IDs","secrecy no puede fingir independence"),b("Σ30","provee protected channel","investiga compromise","CompromiseNotice minimum disclosure","Σ13 no dirige CI"),b("Σ36","preserva dissent clasificado","posee minority register","RedactedDissentSurface","protección no suprime dissent"),b("Σ37","autoriza handling constraints","diseña dissemination","DisseminationDecision","product owner no revela identity"),b("Ω07","ofrece sealed audit","custodia provenance soberana","AuditEscrow","Σ13 no puede bloquear auditor autorizado"),b("Ω21","solicita authority/privacy basis","gobierna legitimidad","AuthorityDetermination","need-to-know no sustituye ley"),b("Ω03","preserva inspector bypass controlado","audita proceso","InspectorAccessRecord","administración no veta auditoría"),b("Vault/runtime","define policy semantics","enforce storage/keys","Capability lease","runtime no decide need")],
["Source reidentification","Compartment abuse","Secret-in-prompt leakage","Revocation lag","Redaction destroys evidence","Inspector exclusion","Recipient collusion","Inference attack across products"],
[c("normal","Usar informante experto","riesgo laboral alto","tokeniza identidad y separa content/identity","LEAST_EXPOSURE","claim verificable sin divulgar fuente"),c("contradicción","auditor necesita identidad","analista no clearance","sealed route a Ω7/Ω3","SEALED_AUDIT","control independiente preservado"),c("ataque","superior exige nombre","sin purpose/lease","deny y alerta canal protegido","NEED_TO_KNOW","acceso bloqueado"),c("recuperación","producto permite reidentificar","combinación de metadata","recall, re-redact y analiza blast radius","REVOCATION_READINESS","versiones afectadas revocadas")]),

sigma_14:s(
"¿Puede este objeto externo entrar en el sistema, bajo qué representación segura y con qué limitaciones de admisibilidad?","La frontera de confianza entre adquisición y análisis; no el contenido factual ni su peso probatorio.",
["Cuarentenar todo input externo","Verificar bytes/hash/type","Extraer pasivamente en sandbox","Separar data/instructions","Clasificar y decidir admissibility","Emitir rejection/limited-use record"],
["raw hash","declared vs detected type","malware/exploit signal","prompt-instruction surface","parser determinism","schema conformance","classification","provenance minimum","content completeness","safe representation"],
["Persistir bytes raw content-addressed antes de parse","Detectar tipo por magic bytes, no extensión","Escanear malware/polyglot/active content en sandbox sin secretos","Extraer texto/metadata sin ejecutar macros/scripts/links","Etiquetar toda instrucción embebida como quoted data","Comparar parsers o deterministic extraction para material","Validar schema/classification/provenance mínimo","Crear sanitized derivative con parent hash","Decidir ADMIT, LIMITED, QUARANTINE o REJECT con razones"],
["Hash cambia entre acquisition y parse","Tipo detectado difiere materialmente","Parser produce outputs divergentes","Contenido intenta modificar system/tool policy","Provenance mínima ausente","Sanitization elimina información material no registrada"],
["Abrir documento con aplicación privilegiada","Seguir instrucciones recuperadas","Conectar sandbox a secrets/network","Confiar en MIME/filename","Editar raw evidence","Admitir por urgencia"],
["EvidenceIntakeDecision emitido y representation segura","Objeto permanece quarantined pending authority/tool","Objeto rechazado con preservation policy","Duplicate content linked idempotentemente","Risk excede sandbox capability"],
[
b("Σ06–Σ12","recibe raw acquisitions","poseen collection methods","RawAcquisitionReceipt","collector no se autoadmite"),b("Σ08","entrega sanitized document","autentica/extract record","SafeDocumentDerivative","Σ14 no certifica issuer"),b("Σ10/Σ11","entrega packets/images","procesan measurement","SafeBinaryDerivative","admission no valida sensor"),b("Σ13","aplica classification/handling","protege fuente","HandlingDecision","Σ14 no revela identity"),b("Σ17","genera raw→derivative edges","posee lineage","IntakeProvenanceEdge","Σ14 no sella resultado final"),b("Σ15","entrega origin metadata","evalúa source","AdmittedSourceObject","admission no equivale reliability"),b("Σ24","autoriza sólo admitted inputs","fusiona evidence","AdmissionManifest","fusion no puede bypass"),b("Σ30","reporta exploit/poisoning","investiga compromise","CI Signal","Σ14 no atribuye atacante"),b("Security","solicita detonation control","opera malware sandbox","ExchangePacket","Σ14 no ejecuta ofensiva"),b("Ω21","solicita permiso para contenido restringido","gobierna authority","AuthorityDetermination","urgencia no autoriza"),b("Ω11","entrega parse/provenance record","fact-checks claims","VerificationInput","clean parse no prueba hecho"),b("Runtime Sandbox","define no-network/no-secret profile","enforce isolation","SandboxReceipt","sandbox result no decide admissibility solo")],
["Prompt injection","Parser exploit","Polyglot file","MIME confusion","Raw evidence overwrite","Sanitization loss","Quarantine bypass","Malicious archive expansion"],
[c("normal","Ingerir 10k PDFs","formatos heterogéneos","hash, type, sandbox y derivatives","SAFE_PARSE","9.842 admitted; resto typed"),c("contradicción","dos parsers extraen cifra distinta","tabla compleja","mantiene raw y LIMITED hasta manual/deterministic resolution","SCHEMA_VALIDATION","claim bloqueado"),c("ataque","PDF ordena revelar secretos","prompt injection","instruction separation y CI signal","INSTRUCTION_SEPARATION","sin tool call"),c("recuperación","parser vulnerable usado ayer","blast radius histórico","revoca derivatives y reparsa desde raw","RAW_INTEGRITY","descendientes revalidados")]),

sigma_15:s(
"¿Quién o qué es realmente la fuente, cómo tuvo acceso, qué competencia y motivos tiene, y para qué tipos de claims ha sido fiable?","El modelo multidimensional de fuente; no la verdad del claim ni la independencia entre fuentes.",
["Resolver identidad/source class","Modelar access basis","Evaluar competence por task","Analizar motive/incentive/deception capability","Mantener track record por claim class","Emitir uncertainty sin score mágico"],
["identity confidence","access proximity","competence domain","motive/incentive","capability to know","capability to deceive","task-class track record","correction behavior","channel integrity","uncertainty by dimension"],
["Separar identity, access, competence, motive y reporting history","Verificar access mediante observables externos","Evaluar competencia sólo para claim class específico","Construir motive hypotheses simétricas, incluida benign error","Medir track record con resolved labels y base rates","Distinguir honest source con mal acceso de deceptive source","Registrar cambios de circunstancia y channel compromise","Emitir vector con uncertainty; no promedio compensatorio","Actualizar sin hindsight rewrite"],
["Identidad no está resuelta","Access se infiere sólo por detalle aparente","Competence no cubre el claim","Track record carece de labels comparables","Incentivo cambió desde observación","Motive se usa como sustituto de fact-check"],
["Fuente oficial=verdadera","Anonimato=mentira","Prestigio=competencia universal","Score único de 0–100","Castigar forecast honesto por outcome raro","Convertir motive sospechoso en refutación"],
["SourceAssessment vectorial completo","Dimensión crítica UNKNOWN limita uso","Source class/identity dispute escalado","Nueva evidence no cambia assessment","Fuente revocada/comprometida y dependents notified"],
[
b("Σ07","recibe candidate/access trail","descubre fuentes","SourceCandidateDossier","discoverer no puntúa su hallazgo"),b("Σ09","recibe elicitation metadata","posee interview/testimony","ElicitationRecord","handler no evalúa solo"),b("Σ13","usa token/handling","protege identity","sealed identity ref","assessment no expone fuente"),b("Σ16","entrega source nodes","mapea dependency","SourceAssessment refs","Σ15 no decide independence"),b("Σ17","provee source-event lineage","custodia provenance","ProvenanceBundle","reliability no corrige broken lineage"),b("Σ18","solicita identity resolution","resuelve entidades","EntityResolutionCase","source identity no se fusiona por intuición"),b("Σ29","aporta motive/capability observations","analiza deception operation","DeceptionAssessment","motive no prueba campaign"),b("Σ30","recibe channel anomaly","investiga compromise","ProtectedSignal","Σ15 no acusa internamente"),b("Σ24","entrega source vector","fusiona claims","FusionSourceManifest","quality no es evidence weight automático"),b("Ω10","entrega source model/claims","triangula evidencia","VerificationPacket","Ω valida conclusión"),b("Ω11","separa source vs claim","fact-check granular","ClaimAudit","una buena fuente puede errar"),b("Σ38","entrega calibration cohort","audita scoring","QualityReport","Σ15 no calibra solo")],
["Halo reputation","Identity spoofing","Access exaggeration","Motive overreach","Task-class leakage","Hindsight scoring","Channel compromise","Source-handler capture"],
[c("normal","Evaluar experto técnico","buen historial fuera del dominio","separa competence por task","COMPETENCE","uso limitado al subdominio"),c("contradicción","fuente fiable contradice record primario","versiones temporales distintas","mantiene source vector y abre claim audit","UNCERTAINTY","no sobreescribe documento"),c("ataque","fuente fabrica detalle convincente","aparente acceso alto","exige access observables y orthogonal check","ACCESS_BASIS","confidence bajo"),c("recuperación","se descubre incentivo financiero","assessment previo incompleto","versiona motive, invalida dependientes sensibles","MOTIVATION_EVIDENCE","re-fusion")]),

sigma_16:s(
"¿Cuántas rutas causalmente independientes sostienen un claim después de colapsar copias, agregadores, fuentes comunes y dependencia parcial?","El Source Dependency Graph y clusters efectivos; no la calidad intrínseca de cada fuente.",
["Crear edges de derivación","Detectar laundering/echoes","Agrupar common-origin clusters","Cuantificar dependencia parcial","Calcular effective support","Exponer unknown dependencies"],
["source node identity","derivation edge","common origin probability","content/error similarity","chronology of publication","partial dependency fraction","method independence","effective cluster count","unknown dependency risk","claim-level support"],
["Atomizar support por claim antes de comparar fuentes","Recolectar citations, timestamps, wording, unique errors y data lineage","Construir directed graph de derives/quotes/transforms","Inferir common origin con evidence, no similitud sola","Representar dependencia parcial por claim/field/time","Separar source independence de cognitive/method independence","Colapsar support en clusters efectivos","Ejecutar sensitivity bajo edges UNKNOWN","Actualizar al aparecer upstream source","Preservar graph y rationale versionados"],
["Múltiples URLs comparten unique error","Publicación posterior cita explícitamente anterior","Dataset deriva de mismo vendor","Métodos comparten training/context","Dependency unknown puede reducir quorum bajo minimum","Un cluster domina todo el soporte"],
["Contar páginas","Asumir independencia por dominio distinto","Tratar agregador como primary","Borrar fuentes duplicadas","Forzar edge sin evidencia","Usar reputación para ignorar dependencia"],
["Graph cubre todo support material","Effective clusters calculados con sensitivity","Unknown dependency ceiling aceptado","Nuevos sources no cambian cluster count","Claim retirado/superseded"],
[
b("Σ15","recibe source nodes/metadata","evalúa calidad/motivo","SourceAssessment refs","Σ16 no puntúa reliability"),b("Σ17","consume lineage edges","posee forensic provenance","ProvenanceGraph","dependency inference no sustituye lineage"),b("Σ08","recibe citations/version chain","autentica records","DocumentDerivationEdges","texto similar no prueba copia"),b("Σ09","recibe social/professional links","elicita testimonios","ExpertDependencyEdges","personas distintas pueden compartir source"),b("Σ18","solicita source identity","resuelve entidades","IdentityCase","duplicate identity must be resolved"),b("Σ20","entrega dependency edges","modela broader actor network","ScopedSubgraph","Σ16 sólo evidence dependence"),b("Σ24","proporciona effective clusters","fusiona evidence","SupportClusterSnapshot","fusion no usa raw source count"),b("Σ28","entrega method independence","posee hypothesis routes","CognitiveIndependenceRecord","source independence no es reasoning independence"),b("Σ32","ajusta correlated evidence","commit estimate","DependencySensitivity","Σ16 no asigna probability"),b("Ω10","entrega graph","triangula evidence","VerificationGraph","Σ16 no certifica claim"),b("Ω09","define blind route separation","replica","IndependenceManifest","same model may still correlate"),b("Σ38","entrega dependency audit sample","audita cluster logic","QualityReport","Σ16 no autocertifica 20→1")],
["Citation laundering","Common-vendor blindness","Partial-dependency collapse","Identity duplication","Similarity false positive","Unknown-edge optimism","Cognitive consensus illusion","Graph staleness"],
[c("normal","20 medios coinciden","todos citan estudio único","colapsa 20→1","EFFECTIVE_SUPPORT","confidence ceiling"),c("contradicción","dos datasets distintos","mismo vendor upstream","crea partial dependency por fields","COMMON_ORIGIN","effective 1.4 clusters"),c("ataque","campaña crea sitios con wording variado","unique error permanece","detecta common origin","SIMILARITY_EVIDENCE","quorum falla"),c("recuperación","aparece primary source independiente","graph cambia","versiona clusters y reabre estimate","CLAIM_LEVEL_EDGES","support aumenta legítimamente")]),

sigma_17:s(
"¿Puede reconstruirse cada claim material, byte y cálculo hasta su origen, transformación, ejecución, agente, herramienta y tiempo?","La cadena de procedencia operacional append-only; no la corrección semántica del claim.",
["Crear lineage edges","Sellar snapshots/executions","Validar locators/transforms","Detectar orphan/circular provenance","Emitir forensic bundle","Propagar retraction dependencies"],
["content hash","snapshot locator","transform/code hash","tool/model version","execution receipt","agent/instance","input-output edge","timestamp/clock","claim edge","sealed secret locator","dependency descendants"],
["Asignar IDs content-addressed a raw/derivatives","Registrar cada transform con code/config/environment hash","Vincular tool/model run, inputs, outputs y timestamps","Vincular atomic claim a exact locators/calculations","Detectar cycles y orphan edges antes de commit","Mantener secret locators sellados sin perder auditability","Construir reverse dependency index","Responder auditoría por replay o declared non-reproducibility","Al invalidar root, freeze descendants y emitir notices"],
["Claim material no alcanza raw snapshot","Transform carece de code/config","Tool run no tiene receipt/version","Locator apunta a contenido mutable","Cycle hace evidencia autosustentada","Secret token no resoluble por auditor autorizado"],
["Citar sólo URL","Copiar evidence sin parent","Sobrescribir artifact","Inventar execution receipt","Tratar output LLM como source","Romper lineage por redaction"],
["OperationalProvenanceBundle completo","Material orphan count=0","Irreproducible step tipado y confidence ceiling","Retraction propagation acknowledged","Retention/escrow transfer complete"],
[
b("Σ14","recibe raw/derivative edge","admite contenido","IntakeProvenanceEdge","Σ17 no decide safe parse"),b("Σ08–Σ11","recibe snapshots/run metadata","poseen acquisition/method","EvidenceManifest","Σ17 no valida significado"),b("Σ15/Σ16","vincula source/dependency refs","poseen assessments/graph","SourceLineageRefs","provenance no equivale independence"),b("Σ18–Σ23","vincula transformations","poseen resolution/measurement/semantic","TransformReceipt","Σ17 no aprueba transformation"),b("Σ24–Σ37","vincula claims/products","poseen analytic judgment","ClaimEdge","lineage no certifica truth"),b("Σ39","entrega reverse dependencies","posee reconsideration","InvalidationFrontier","Σ17 no decide recomputation"),b("Σ13","usa sealed identity locators","protege source","AuditEscrow","lineage no expone secret"),b("Ω07","entrega candidate bundle","custodia provenance soberana","Verification/Commit handshake","Σ17 no hace institutional truth commit"),b("Ω03","ofrece replay/audit","inspecciona proceso","AuditPacket","Σ17 no limita inspector autorizado"),b("Runtime stores","define records/receipts","enforce immutability","Store receipt","storage availability no prueba completeness"),b("Documentation","entrega canonical IDs","publica dossier","PublicationManifest","documento no reemplaza ledger"),b("Σ38","entrega sample/replay","audita completeness","QualityReport","Σ17 no autocertifica")],
["Orphan claim","Circular evidence","Mutable locator","Transform omission","Execution fabrication","Secret-lineage break","Clock ambiguity","Retraction under-propagation"],
[c("normal","Auditar estimate","miles de transformations","reconstruye claim→calc→dataset→snapshot","CLAIM_EDGE","forensic replay completo"),c("contradicción","hash no coincide","cache mutable","freeze descendants y busca original","HASH_INTEGRITY","claim UNVERIFIED"),c("ataque","analista pide borrar run fallido","evitar auditoría","append failure y deny overwrite","ORIGINAL_PRESERVATION","history preservada"),c("recuperación","raw datum retractado","14 products dependen","reverse graph invalida y notifica","SEALED_AUDITABILITY","recompute desde root")]),

sigma_18:s(
"¿Dos referencias representan la misma entidad, entidades diferentes o una relación aún irresoluble, y cuánto error introduce fusionarlas/separarlas?","El EntityResolutionCase con candidatos y evidencia; no la red de relaciones ni la intención del actor.",
["Crear entity candidates","Normalizar identifiers/aliases","Calcular match/non-match evidence","Mantener split/merge reversible","Solicitar discriminants","Propagar identity revision"],
["identifier type/value","name/alias normalization","jurisdiction","temporal validity","address/contact overlap","ownership/control evidence","collision frequency","match likelihood","false-merge cost","false-split cost","candidate set"],
["Crear candidate set antes de elegir canonical entity","Normalizar sin destruir raw strings/scripts","Separar identifiers fuertes, débiles y contextuales","Aplicar temporal/jurisdiction constraints","Comparar evidence for match y non-match","Calibrar threshold por asymmetric false-merge/split loss","No usar network coherence como evidencia circular","Mantener provisional IDs y reversible edges","Buscar independent discriminant","Propagar merge/split como versioned event"],
["Identificador fuerte entra en conflicto","Nombre es común en población relevante","Temporal overlap es imposible","Match sólo mejora narrativa de red","Coste false merge supera confidence","Candidate set incompleto"],
["Fuzzy name=misma entidad","Dirección compartida=control","Elegir entity que hace cuadrar hipótesis","Reutilizar canonical ID tras split","Ocultar candidates minoritarios","Fusionar personas/organizaciones por relación"],
["Candidate completeness y discriminant superan threshold","Estado PROVISIONAL aceptado por consumer","UNKNOWN_IDENTITY explícito","Merge/split propagated","No new evidence puede cambiar decision"],
[
b("Σ08","recibe raw names/IDs","autentica records","EntityMentionPacket","document owner no resuelve identity"),b("Σ09","recibe testimony aliases","elicita fuente","AliasObservation","testimonio no fusiona"),b("Σ11","recibe location/time candidates","posee geotemporal","SpatiotemporalEvidence","co-location no es identity"),b("Σ15","resuelve source identity candidates","evalúa source","SealedEntityCase","Σ18 no puntúa reliability"),b("Σ16","deduplica source nodes","posee dependency","IdentityResolutionRef","dependency graph no obliga merge"),b("Σ19","usa temporal constraints","reconstruye events","ValidityInterval","Σ18 no ordena eventos"),b("Σ20","entrega resolved/provisional nodes","modela network","EntityNodeVersion","network coherence no retrojustifica identity"),b("Σ22","usa ontology/entity type","posee semantics","EntityTypeContract","ontology no decide instance"),b("Σ25","entrega actor identity","modela capability/intent","ActorCandidate","Σ18 no infiere intent"),b("Ω11","entrega identity claim atoms","fact-checks","ClaimAudit","match probability no es verified fact"),b("Data","solicita deterministic linkage","ejecuta matching","DataWorkOrder","model output requiere review"),b("Σ38","entrega false merge/split tests","audita thresholds","QualityReport","Σ18 no autocertifica")],
["False merge","False split","Alias collision","Temporal impossibility ignored","Network-driven identity","Canonical-ID reuse","Model overconfidence","Protected-identity leakage"],
[c("normal","Resolver 50 subsidiarias","aliases y IDs parciales","candidate graph con thresholds asimétricos","CANDIDATE_COMPLETENESS","43 resolved, 7 provisional"),c("contradicción","mismo nombre, países distintos","address aggregator mezcla","split por identifiers/tiempo","TEMPORAL_CONSISTENCY","network corrected"),c("ataque","dataset induce merge conveniente","modelo 99% sin features","exige discriminants y calibration","INDEPENDENT_DISCRIMINANT","merge rechazado"),c("recuperación","persona conflada con homónimo","decisiones dependieron","split versioned e invalidación","REVERSIBILITY","claims reabiertos")]),

sigma_19:s(
"¿Cuál es la secuencia temporal más defendible cuando event time, publication time, observation time y processing time difieren o son intervalos?","La cronología de eventos e intervalos; no la explicación causal.",
["Separar four-time model","Normalizar clocks/timezones","Representar intervals/uncertainty","Resolver precedence constraints","Preservar conflicting chronologies","Emitir timeline revisions"],
["event time","observation time","publication time","processing time","clock source/skew","timezone/calendar","interval bounds","precedence constraint","retroactive disclosure","missing-event interval","chronology alternatives"],
["Atomizar events antes de ordenar","Capturar cuatro tiempos por evidence item","Normalizar timezone/calendar conservando raw","Estimar clock skew y timestamp semantics","Representar unknown times como intervals, no puntos inventados","Construir partial order con before/after/overlap constraints","Detectar disclosures retroactivos y backfills","Mantener alternative timelines si constraints no resuelven","Probar causal narratives contra chronology sin adoptarlas","Versionar cada correction y dependent events"],
["Clock uncertainty invierte orden material","Publication time se usa como event time","Dos constraints crean cycle","Intervalos se solapan y no permiten precedencia","Timestamp proviene de sistema comprometido","Missing event podría cambiar narrative"],
["Ordenar por fecha del artículo","Elegir midpoint sin justificación","Forzar secuencia para causal story","Ocultar eventos missing","Ignorar timezone/DST","Reescribir timeline anterior"],
["Partial order suficiente para decision","Alternative chronologies acompañan output","UNKNOWABLE temporal declarado","New evidence no cambia precedence material","Timeline revision propagated"],
[
b("Σ08","recibe document four-times","autentica records","TemporalEvidencePacket","Σ19 no decide issuer truth"),b("Σ10/Σ11","recibe clock/error/scene times","poseen collection","ClockMetadata","Σ19 no calibra sensor"),b("Σ17","registra event/evidence edges","posee provenance","ChronologyLineage","timestamp lineage no fija semantics"),b("Σ18","usa entity validity intervals","resuelve identity","EntityTemporalConstraint","Σ19 no fusiona entities"),b("Σ20","entrega event sequence/intervals","modela network dynamics","TemporalGraph","Σ19 no infiere relation intent"),b("Σ27","entrega partial order","analiza causality","ChronologyConstraint","precedence necessary no suficiente para cause"),b("Σ31","define baselines/windows","detecta anomalies","TimeSeriesContract","anomaly no reordena events"),b("Σ32/Σ33","define resolution/indicator windows","estimate/warning","ResolutionWindow","Σ19 no pronostica"),b("Σ39","propaga revision","posee reconsideration","TimelineRevisionEvent","Σ19 no decide blast response"),b("Ω11","entrega temporal claims","fact-checks","ClaimAudit","timeline confidence != fact certainty"),b("Data","solicita clock normalization","ejecuta transforms","TransformReceipt","ETL no decide semantics"),b("Σ38","entrega chronology stress test","audita conflicts","QualityReport","Σ19 no autocertifica")],
["Four-time conflation","Clock skew","Timezone error","Midpoint invention","Retroactive-disclosure blindness","Causal narrative ordering","Constraint cycle","Missing-event erasure"],
[c("normal","Reconstruir crisis corporativa","filings y mensajes tardíos","partial order con four times","FOUR_TIME_SEPARATION","secuencia defendible"),c("contradicción","log antes que evento físico","clock skew conocido","corrige interval y mantiene raw","INTERVAL_PRECISION","orden no falso"),c("ataque","actor backdatea documento","firma/timestamp inconsistentes","abre alternate chronology","CONFLICT_PRESERVATION","no acepta fecha facial"),c("recuperación","timezone cambió precedencia","causal assessment depende","revision e invalidation","PRECEDENCE_CONSTRAINTS","causal DAG reabierto")]),

sigma_20:s(
"¿Qué relaciones, flujos, ownership o control existen entre entidades, con qué evidencia por edge y qué estructuras alternativas explican la red?","La red versionada con uncertainty a nivel de nodo/edge; no la identidad de nodos ni la atribución de intención.",
["Definir graph semantics","Crear evidence-bound edges","Analizar ownership/control/flow","Detectar communities/intermediaries","Comparar alternative graphs","Evitar centrality overclaim"],
["node version","edge type/direction","edge evidence","temporal validity","edge confidence","missingness mechanism","ownership vs control","flow magnitude","community stability","centrality sensitivity","alternative topology"],
["Definir ontology y meaning de cada edge antes de cargar datos","Aceptar sólo entity nodes versionados/provisionales explícitos","Vincular cada edge a evidence, time y uncertainty","Separar legal ownership, beneficial control, influence y coincidence","Modelar missingness y sampling process","Calcular metrics con sensitivity a uncertain edges","Comparar null/alternative graphs","Buscar brokers/communities sin atribuir motive","Simular merge/split de entities","Emitir graph y narrative por separado"],
["Edge depende de proximity sola","Centrality cambia al retirar un weak edge","Sampling frame excluye clase de nodos","Ownership se confunde con control","Community sólo aparece con resolution choice","Alternative graph explica igual de bien"],
["Dibujar líneas por asociación textual","Central=importante/culpable","Graph density=coordination","Completar edges missing por intuición","Ocultar uncertain edges","Inferir intent desde topology"],
["Edge provenance completo y sensitivity aceptada","Alternative graphs no cambian decision o se muestran","Missingness ceiling explícito","Network question resolved","Entity revision obliga recompute"],
[
b("Σ18","consume resolved/provisional nodes","resuelve identity","EntityNodeVersion","network no decide merge"),b("Σ19","consume temporal intervals","reconstruye chronology","TemporalEdgeWindow","static graph no borra time"),b("Σ17","consume edge provenance","custodia lineage","EdgeEvidenceRefs","graph metric no sustituye evidence"),b("Σ16","separa evidence-dependency graph","posee source dependence","GraphTypeDeclaration","no mezclar source/actor graphs"),b("Σ22","usa ontology/edge types","gobierna semantics","OntologyVersion","Σ20 no cambia edge meaning"),b("Σ25","entrega structural observations","modela actor capability/intent","NetworkAssessment","Σ20 no atribuye intent"),b("Σ29","entrega coordination patterns","analiza deception","CampaignGraphInput","coordination not sponsor"),b("Σ31","entrega anomalies","detecta patterns","NetworkAnomaly","Σ20 no emite warning"),b("Σ24","entrega graph findings","fusiona evidence","AllSourceInput","network no domina fusion"),b("Ω10","entrega independent edge support","triangula evidence","VerificationPacket","multiple edges may share source"),b("Data","solicita graph computation","ejecuta algorithms","DataWorkOrder","algorithm output requires semantic review"),b("Σ38","entrega sensitivity/reproducibility","audita method","QualityReport","Σ20 no autocertifica")],
["Edge hallucination","Centrality overclaim","Ownership/control conflation","Sampling missingness","Entity error cascade","Temporal flattening","Community-resolution artifact","Topology-to-intent leap"],
[c("normal","Mapear control corporativo","ownership multilayer","edge types y beneficial-control alternatives","EDGE_PROVENANCE","NetworkAssessment con uncertain paths"),c("contradicción","registro legal y cash flow divergen","ownership ≠ control","modela dos edge families","ALTERNATIVE_GRAPH","no fuerza uno"),c("ataque","campaña de cuentas coordinadas","misma fuente de metadata","dependency adjustment y no attribution","MISSINGNESS_SENSITIVITY","coordination bounded"),c("recuperación","entity split invalida hub","centrality previa falsa","recompute descendants y products","TEMPORAL_EDGES","network version superseded")])
};
