import{spec as s,boundary as b,scenario as c}from"./spec-helper.mjs";
export default {
sigma_31:s(
"¿Qué desviaciones respecto a un baseline válido son señales persistentes y decision-relevant, y cuáles son artefactos de medición, pipeline, múltiples tests o azar?","El portfolio de patrones, anomalías y weak signals; no la explicación causal ni el warning.",
["Define baseline/regime","Detect candidate anomalies","Control multiple testing","Exclude artifacts","Seek orthogonal persistence","Promote weak signal or dismiss"],
["baseline population/window","regime/method version","expected variance","candidate deviation","multiple-test burden","artifact likelihood","persistence","cross-domain coherence","effect magnitude","decision relevance","novelty"],
["Definir baseline y regime antes de observar spike","Verificar pipeline/method/version y denominator","Aplicar seasonal/trend adjustment documentado","Controlar false discovery o predeclare tests","Distinguir point, contextual, collective y change-point anomaly","Buscar artifact/data-quality explanations primero","Exigir persistence o orthogonal signal proporcional a materiality","Comparar against null/reference distribution","Separar anomaly detection de explanation","Promover con evidence/uncertainty y trigger"],
["Baseline contiene el evento que intenta detectar","Pipeline/version change explica desviación","Significance desaparece tras multiple testing","Effect menor que measurement error","Signal no persiste ni tiene orthogonal support","Decision relevance es nula"],
["Outlier=insight","Cherry-pick window","Cambiar baseline post hoc","Ignorar false discoveries","Causalizar patrón","Emitir warning sin threshold owner"],
["AnomalyPortfolio validated/dismissed","False discovery controlled","Weak signal transferred to hypothesis/watch","Baseline invalid triggers RETURN","Marginal scanning under threshold"],
[
b("Σ21","consume measurement/error/regimes","owns comparability","MeasurementAssessment","Σ31 no arregla data"),b("Σ19","consume time intervals","owns chronology","TimeSeriesContract","anomaly not event order"),b("Σ20","consume network metrics","owns graph","NetworkAnomalyInput","centrality shift may be topology artifact"),b("Σ24","provides anomaly finding","owns fusion","AnomalyPortfolio","Σ31 not fuse all evidence"),b("Σ27","hands candidate pattern","tests causality","CausalQuery","anomaly not mechanism"),b("Σ28","hands signal","creates hypotheses","ObservationPacket","anomaly not favored hypothesis"),b("Σ29","hands coordination/spoof pattern","tests deception","DeceptionInput","anomaly not attack"),b("Σ32","hands feature/signpost","owns estimate","AnomalyFeature","Σ31 not probability"),b("Σ33","hands validated indicator candidate","owns warning","IndicatorCandidate","Σ31 not alert"),b("Σ34","hands weak/edge signal","owns surprise","SurpriseInput","novelty not tail importance"),b("Data","specifies deterministic scan","executes stats","DataWorkOrder","model output requires context"),b("Σ38","provides preregistration/FDR audit","audits tradecraft","QualityReport","Σ31 not self-certify")],
["Baseline contamination","Pipeline artifact","Multiple-testing false discovery","Window cherry-pick","Seasonality blindness","Weak-signal hype","Pattern-to-cause leap","Novelty bias"],
[c("normal","Detect early capacity build","noisy orders","baseline/FDR/persistence","BASELINE","weak signal promoted"),c("contradiction","orders spike, employment flat","pipeline reclassification","artifact exclusion","ARTIFACT_EXCLUSION","spike dismissed"),c("attack","analyst scans until p<.05","unlogged tests","recompute test burden","MULTIPLE_TESTING","claim rejected"),c("recovery","baseline regime changed","warning indicator depended","supersede baseline","PERSISTENCE","watch recalibrated")]),

sigma_32:s(
"¿Qué quantity/event/range is expected by a resolvable horizon, with what calibrated uncertainty, assumptions, signposts and update policy—distinct from simulation?","El EstimateRecord pre-outcome y resoluble; no la estrategia, warning threshold o simulation output.",
["Define resolvable question","Set reference class/prior","Integrate evidence dependency-aware","Produce calibrated range/probability","Precommit resolution/update","Score resolved estimates"],
["target event/quantity","resolution source/date","reference class","base rate/prior","likelihood evidence","dependency adjustment","forecast horizon","uncertainty distribution","precision ceiling","signposts","update rule","calibration cohort"],
["Operationalize resolvable target and authoritative resolution source","Select/document reference class and base rate","Separate model forecast, scenario and simulation","Build outside-view prior before case evidence","Update using diagnostic evidence adjusted for dependence","Run sensitivity/model ensemble without averaging incompatible targets","Set precision ceiling from data/model calibration","Precommit range/probability before outcome","Define signposts and update thresholds","Score Brier/log/interval after resolution without rewriting"],
["Question cannot resolve objectively","Reference class is selected post-outcome","Evidence dependencies unmodeled","Model disagreement exceeds reported interval","Precision exceeds historical calibration","Forecast horizon crosses regime with no scenario"],
["Single-point forecast","Probability from prose intuition alone","Backcast after outcome","Simulation frequency=real probability","Narrow interval to satisfy sponsor","Change resolution criterion"],
["EstimateRecord frozen and reviewable","Target resolved/scored","Update trigger crossed and superseding version issued","UNFORECASTABLE/UNKNOWN bounded","Decision no longer sensitive"],
[
b("Σ03","receives resolvable question","owns requirement","ResolutionCriteria","Σ32 not move target"),b("Σ21","consumes measurement/error","owns comparability","MeasurementAssessment","forecast cannot outrun precision"),b("Σ24","consumes fused evidence","owns fusion","AllSourceFusion","Σ32 not re-fuse"),b("Σ28","consumes hypothesis set","owns alternatives","HypothesisSet","Σ32 commits probabilities"),b("Σ26/27","consumes regime/mechanism","own context/causal","ModelInputs","estimate not causal proof"),b("Σ31","consumes anomaly/signposts","owns pattern validation","AnomalyPortfolio","Σ32 not promote raw anomaly"),b("Σ33","provides estimate/signposts","owns warning threshold","EstimateRecord","forecast not alert"),b("Σ34","receives surprise challenge","owns discontinuities","TailChallenge","estimate must show omitted tails"),b("Ω16","distinguishes forecast/simulation","simulates","SimulationReport","simulation not forecast"),b("Ω17","delivers uncertainty","designs strategy","EstimateRecord","Σ32 not recommend action"),b("Ω09/10","submits material estimate","replicate/triangulate","VerificationPacket","Σ32 not sole certifier"),b("Σ38","provides calibration scoring","audits quality","CalibrationReport","Σ32 cannot score itself only")],
["Reference-class gaming","False precision","Resolution drift","Dependency double-count","Hindsight rewrite","Scenario-probability conflation","Regime extrapolation","Calibration cohort cherry-pick"],
[c("normal","Plant online in 18 months","reference projects available","prior/update/range","REFERENCE_CLASS","35–55% frozen"),c("contradiction","inside view 80%, outside 30%","assumptions differ","sensitivity and dissent","PRECISION_CEILING","wide range"),c("attack","sponsor demands 82%","no calibration support","refuse precision","PRE_OUTCOME_COMMIT","bounded estimate"),c("recovery","resolution source revised","scoring ambiguous","apply precommitted adjudication","RESOLVABLE_QUESTION","record retained")]),

sigma_33:s(
"¿Han cruzado indicadores preregistrados un threshold que exige alertar a consumidores autorizados dentro de su decision window, pese a false-alarm, staleness and spoofing risks?","El watch, indicator logic y WarningNotice; no la estimación subyacente ni la decisión operativa.",
["Register indicators/thresholds","Maintain persistent watch","Validate freshness/spoofing","Apply combination rule","Issue/upgrade/downgrade warning","Obtain acknowledgment/resolution"],
["indicator definition","observable/source","baseline/threshold","combination rule","freshness TTL","spoofability","false-positive/negative loss","decision window","warning state","consumer/ack deadline","resolution condition"],
["Derive indicator from hypothesis/decision before monitoring","Register source, threshold, direction, TTL and combination rule","Monitor event-driven with gap telemetry","Validate freshness, measurement and source dependence at crossing","Test spoofing/denial and alternative explanations","Apply state machine NORMAL→WATCH→WARNING→CRITICAL without hindsight","Tailor severity to decision window/loss, not rhetoric","Disseminate to authorized consumer and require ACK/disposition","Track false alarm/miss and resolve/downgrade explicitly","Retire stale indicators with history preserved"],
["Indicator was registered after event","Source stale or dependency collapsed","Threshold crosses due method change","Adversary can cheaply spoof all indicators","Consumer window already closed","Combination rule was altered post-crossing"],
["Alert on intuition without registry","Suppress because confidence imperfect","Issue repeated alerts without state change","Treat forecast as warning","Hide false alarms","Assume delivery=acknowledgment"],
["Warning acknowledged/resolved","Watch remains active with next check","Indicator invalidated and replaced","Decision window closes with miss review","Authority/dissemination blocks escalated"],
[
b("Σ03","consumes indicator requirements","owns PIR/EEI","IndicatorRequirement","Σ33 not redefine objective"),b("Σ31","consumes validated signals","owns anomaly","IndicatorCandidate","raw anomaly not alert"),b("Σ32","consumes estimates/signposts","owns forecast","EstimateRecord","probability not threshold alone"),b("Σ34","maintains expected watch","owns surprise search","Watch/Surprise split","registered indicators not whole future"),b("Σ29","consumes spoofing assessment","owns deception","SpoofingRisk","Σ33 not attribute"),b("Σ13/37","defines recipients/handling","own protection/product","DisseminationDecision","warning urgency not bypass clearance"),b("Σ36","surfaces dissent on warning","owns minority","WarningDissent","dissent not suppress warning"),b("Σ39","hands over active watch","owns continuity","WatchHandover","shift change not reset state"),b("Σ40","freezes warning record","evaluates hits/misses","OutcomeReview","Σ33 not score post hoc"),b("Operations/Security","sends warning","owns response","WarningNotice/ACK","Σ33 not execute response"),b("Ω19","escalates existential warning","owns resilience/risk decision","CriticalWarning","Σ33 not accept risk"),b("Σ38","independent duty review","audits threshold","QualityReport","warning owner not sole release reviewer")],
["Stale indicator","Threshold hindsight","Spoofed crossing","Warning suppression","Alert fatigue","Acknowledgment illusion","Decision-window miss","State-machine oscillation"],
[c("normal","Competitor launch imminent","two of three indicators cross","freshness/spoofing + duty review","THRESHOLD_LOGIC","WarningNotice ACK"),c("contradiction","one critical stream stale","others cross","exclude stale and apply rule","FRESHNESS","warning bounded"),c("attack","actor triggers cheap indicator","spoofing known","requires hard-to-fake companion","SPOOFING_CHECK","WATCH not warning"),c("recovery","consumer never received alert","delivery receipt false","escalate ACK miss and review channel","CONSUMER_AUTHORITY","dissemination repaired")]),

sigma_34:s(
"¿Qué discontinuities, regime shifts, tail mechanisms or adjacent-domain changes are missing precisely because current models and indicators agree?","La superficie de sorpresa estratégica y tripwires de discontinuidad; no fantasías ilimitadas ni probabilidad falsa.",
["Map shared assumptions","Invert boundaries","Search edge domains/history","Generate distinct tail mechanisms","Design tripwires/resilience relevance","Retire fantasy cases"],
["shared assumption","model boundary","discontinuity mechanism","historical analogue","adjacent-domain signal","tail consequence","plausibility constraint","tripwire","resilience implication","detection blind spot"],
["Inventory assumptions shared across models/providers","Identify boundaries/exogenous variables treated as fixed","Invert each critical assumption","Search historical base rates and adjacent domains","Generate mechanism chains with enabling conditions","Reject cases violating physics/institutional constraints","Separate possibility, plausibility and probability","Design early tripwires not already in watch","Evaluate resilience relevance even if unquantifiable","Maintain portfolio diversity and retirement criteria"],
["Mechanism lacks enabling path","Historical analogue is superficial","Case duplicates existing indicator","Possibility cannot affect decision/resilience","Tripwire cannot observe before impact","Tail story is unfalsifiable"],
["Science-fiction list","Assign arbitrary tiny probabilities","Reward novelty alone","Duplicate red team","Treat unknown unknowns as known","Consume core verification reserve indiscriminately"],
["StrategicSurpriseAssessment with distinct mechanisms","Tripwires assigned or observability UNKNOWN","Resilience implication handed off","Mechanism retired by evidence","Marginal search yields duplicates"],
[
b("Σ26","challenges boundaries/regimes","owns system model","BoundaryChallenge","Σ34 not rebuild whole model"),b("Σ28","adds edge hypotheses","owns hypothesis portfolio","SurpriseHypothesis","tail not ordinary alternative"),b("Σ31","consumes weak signals","owns anomaly validation","WeakSignalPacket","novel anomaly not discontinuity"),b("Σ33","designs new tripwire","owns watch","TripwireCandidate","Σ34 not issue alert"),b("Σ32","challenges forecast tails","owns estimate","TailChallenge","Σ34 not assign unsupported probability"),b("Σ35","hands favorable discontinuity","owns opportunity","OpeningCandidate","tail upside not opportunity until validated"),b("Σ19","hands downside/resilience","owns existential risk","SurpriseAssessment","Σ34 not decide risk acceptance"),b("Ω15","coordinates unconventional alternatives","owns sovereign reframing","AlternativePacket","Σ34 domain is strategic surprise"),b("Ω16","hands mechanisms/scenarios","simulates","ScenarioCommission","simulation not probability"),b("Ω18","hands cross-domain path","evaluates impact","ImpactInput","Σ34 not evaluate all orders"),b("Research","commissions analogue search","executes research","ResearchCommission","analogue not proof"),b("Σ38","audits novelty/grounding","owns quality","QualityReport","Σ34 not self-certify imagination")],
["Fantasy proliferation","Shared-assumption blindness","Analogue superficiality","Tail probability fabrication","Tripwire duplication","Novelty Goodhart","Edge-domain omission","Resilience irrelevance"],
[c("normal","Provider dominance assumed","adjacent substitute emerges","boundary inversion/history/tripwire","HISTORICAL_GROUNDING","three mechanisms"),c("contradiction","tail plausible but no early signal","low observability","resilience handoff","TRIPWIRES","UNKNOWN detection"),c("attack","team generates 100 wild ideas","novelty metric","mechanism/prerequisite filter","MECHANISM_DISTINCTNESS","four survive"),c("recovery","prediction failure exposes assumption","all models shared","open surprise case/update register","SHARED_ASSUMPTION_MAP","watch expanded")]),

sigma_35:s(
"¿Existe una favorable opening with a real mechanism, finite window, magnitude, prerequisites and validation path—or only hype, selection bias or adverse selection?","La oportunidad estratégica observada y option-value evidence; no la asignación de capital ni la estrategia.",
["Detect opening mechanism","Estimate window/magnitude","Map prerequisites/competition","Test mirage/adverse selection","Design validation path","Issue opportunity assessment"],
["opening mechanism","window start/end","magnitude basis","required capabilities","competition/crowding","adverse selection","option value","irreversibility","validation experiment","signposts","downside asymmetry"],
["State causal mechanism creating opening","Bound start/end and what closes window","Estimate magnitude with denominator/range","Map prerequisites and unavailable capabilities","Model competitor response/crowding","Generate mirage and adverse-selection hypotheses","Compare pilot/reservation/wait/no-action option value","Separate reversible learning action from commitment","Define cheapest decisive validation","Publish signposts and expiration"],
["No mechanism beyond trend","Window cannot be observed","Magnitude denominator invalid","Prerequisite unavailable before close","Opportunity vanishes under competitor response","Same signal explained by adverse selection"],
["Large TAM=opportunity","Ignore execution prerequisites","Recommend investment","Hide downside to preserve excitement","Treat uncertainty as upside","Move window after miss"],
["OpportunityAssessment with validation path","Mirage rejected/retained explicitly","Window expires","Validation disproves opening","Handed to strategy/capital owners"],
[
b("Σ31/34","consumes favorable anomaly/discontinuity","own anomaly/surprise","OpeningCandidate","novelty not opportunity"),b("Σ26/27","consumes system/mechanism","own environment/causal","MechanismAssessment","Σ35 not invent cause"),b("Σ21/32","consumes magnitude/uncertainty","own measurement/estimate","QuantitativeInputs","Σ35 not narrow range"),b("Σ25","consumes actor/competitor model","owns actor analysis","CompetitionModel","Σ35 not assume passive rivals"),b("Σ28","maintains mirage alternatives","owns hypotheses","MirageHypothesis","opportunity owner cannot omit null"),b("Σ37","delivers balanced finding","owns product","OpportunityBrief","product not sales deck"),b("Σ36","preserves skeptical minority","owns dissent","OpportunityDissent","upside doesn't bury warning"),b("Ω17","delivers opening/options","designs strategy","OpportunityAssessment","Σ35 not choose action"),b("Ω18/19","delivers downside pathways","impact/risk","RiskInput","Σ35 not accept existential risk"),b("Ω20","delivers value/requirements","allocates capital","ResourceOption","Σ35 not fund"),b("Product/Engineering","commissions validation","execute pilot","ExperimentArtifact","Σ35 not build"),b("Σ38","audits hype/denominator","owns quality","QualityReport","Σ35 not self-certify")],
["Opportunity hype","TAM substitution","Window fiction","Prerequisite blindness","Competitor passivity","Adverse-selection omission","Upside-only framing","Experiment theater"],
[c("normal","Rival exits scarce market","capacity window","mechanism/prereq/options","MECHANISM_WINDOW","pilot option"),c("contradiction","demand high; margins fall","crowding/adverse selection","mirage hypotheses","MIRAGE_HYPOTHESIS","opportunity conditional"),c("attack","sponsor wants investment memo","confirmation pressure","separate assessment from decision","VALIDATION_PATH","no capital recommendation"),c("recovery","window closed early","competitor entered","expire assessment/notify","COMPETITION","strategy reopens")]),

sigma_36:s(
"¿Qué material contradictions, minority judgments and unresolved alternatives would change a decision if true, and how must they remain visible until resolved?","El register de contradicción/disenso y su resolution plan; no un veto automático ni false balance.",
["Atomize disagreements","Bind evidence/methods","Assess materiality","Protect minority report","Design resolution plan","Enforce downstream visibility"],
["claim pair/set","exact disagreement","scope alignment","support/contrary evidence","method/source independence","materiality to decision","minority rationale","resolution discriminant","owner/deadline","downstream visibility","status"],
["Split compound disagreements into atomic claims","Verify same scope/time/definition before calling contradiction","Bind each judgment to evidence, method and assumptions","Distinguish factual conflict, interpretation, value and model choice","Assess materiality by decision-switch test","Preserve minority language without dilution","Detect false balance where one side lacks evidence","Assign discriminant/owner/deadline or UNRESOLVABLE","Attach dissent at decision surface, not appendix","Close only with evidence/rationale and notify"],
["Claims differ in scope rather than truth","Minority could switch decision and is hidden","Resolution plan merely votes","One side has no evidence and creates false balance","Producer edits minority wording","Contradiction closed without downstream notification"],
["Majority vote=truth","Every objection equal","Bury footnote","Force consensus for neat product","Allow anonymous unsupported sabotage","Erase dissent after decision"],
["DissentRegisterDelta visible/owned","Contradiction resolved with evidence","UNRESOLVABLE accepted","Decision no longer material but history retained","Retraction/reconsideration triggered"],
[
b("Σ24","receives contradiction from fusion","owns fusion","ContradictionCase","Σ24 cannot average away"),b("Σ28","receives alternative judgments","owns hypotheses","HypothesisDissent","Σ36 not construct all hypotheses"),b("Σ32/33","attaches estimate/warning dissent","own estimate/warning","MinorityReport","dissent not automatic suppression"),b("Σ37","requires surface placement","owns product","DissentSurfaceContract","editor cannot paraphrase materially"),b("Σ38","protects/validates process","owns quality","DissentAudit","Σ36 not sole judge of own materiality"),b("Σ01","reports protected conflicts","commands department","EscalationPacket","Σ1 cannot command consensus"),b("Ω13/14/15","feeds assumptions/attacks/options","own adversarial functions","ChallengePacket","Σ36 preserves results"),b("Ω12","aligns epistemic language","owns institutional states","EpistemicReview","minority status not VERIFIED"),b("Ω23","preserves in dossier","owns sovereign synthesis","DissentManifest","compression cannot delete"),b("Human decision owner","shows material dissent","decides/accepts risk","Acknowledgment","vote not truth"),b("Σ39","registers reopen triggers","owns reconsideration","DissentDependency","closed dissent can reopen"),b("Σ40","uses outcome for process learning","owns effectiveness","FrozenDissentRecord","outcome doesn't retroactively silence")],
["Dissent burial","False consensus","False balance","Scope-mismatch contradiction","Majority coercion","Minority sabotage","Resolution-by-vote","Post-decision erasure"],
[c("normal","Two market ranges","methods differ","atomic disagreement/materiality","ATOMIC_DISAGREEMENT","minority surfaced"),c("contradiction","claims use different definitions","not true contradiction","scope alignment","SUBSTANTIVE_TEST","reclassify"),c("attack","executive orders footnote","decision could switch","protected escalation","DOWNSTREAM_VISIBILITY","product blocked"),c("recovery","minority later correct","decision depended","reopen and propagate","RESOLUTION_PLAN","postmortem no hindsight rewrite")]),

sigma_37:s(
"¿Cómo transformar verified/qualified findings into the right product for an authorized audience without destroying uncertainty, dissent, provenance, correction paths or decision relevance?","El producto y dissemination decision; no la creación de evidence, la certificación final o la decisión.",
["Select product type/audience","Compose claim-based narrative","Preserve epistemic language/dissent","Compress with omission manifest","Authorize dissemination","Recall/supersede products"],
["consumer/audience","decision/use","product type","claim inventory","epistemic label","dissent surface","compression ratio","omission risk","classification/compartment","distribution list","correction path","acknowledgment"],
["Validate consumer decision and authority","Choose warning, estimate, brief, dossier or technical annex by use","Build from claim ledger, never free narrative","Separate fact, inference, estimate, scenario and recommendation owners","Surface material uncertainty/dissent at point of use","Compress hierarchically with omission manifest/drill-down","Apply classification/need-to-know/redaction","Run claim-to-source link and number consistency checks","Obtain quality/release approval distinct from author","Track distribution, ACK, recall and superseding version"],
["Audience lacks authority","Compression changes epistemic force","Material dissent disappears","Claim cannot drill down","Redaction breaks meaning","Product type induces false certainty","Correction cannot reach recipients"],
["Polished prose as quality","Executive summary without caveats","Copy claim without ID","Publish because deadline","Mix intelligence and recommendation","Overwrite prior version"],
["IntelligenceProduct released/ACK","Dissemination denied/limited","Product recalled/superseded","Consumer deadline passes with typed partial","No material omission unresolved"],
[
b("Σ05","uses consumer model","owns decision utility","AudienceContract","Σ37 not invent user"),b("Σ24/32/33/35","consumes findings/estimate/warning/opportunity","own content judgments","ProductInputManifest","editor not alter conclusions"),b("Σ36","preserves dissent surface","owns dissent","DissentManifest","product cannot bury"),b("Σ13","applies handling/redaction","owns protection","HandlingPlan","editor not reveal source"),b("Σ17","links claims/drill-down","owns provenance","ProvenanceBundle","product not ledger"),b("Σ38","submits draft","owns quality release","QualityDecision","author not certify"),b("Σ39","registers recall/triggers","owns continuity","ProductVersionLink","publication not final forever"),b("Ω23","delivers intelligence product","builds sovereign dossier","HandoffPacket","Σ37 not sovereign synthesis"),b("Ω22","receives release evidence","certifies final standard","Certification","Σ37 not final guardian"),b("Ω21","requests sensitive dissemination","authorizes legitimacy","AuthorityDetermination","need not equal permission"),b("Documentation","publishes approved representation","owns publication mechanics","PublicationReceipt","docs not edit canonical content"),b("Human consumer","receives/acknowledges","decides","ACK/Disposition","delivery not use")],
["Compression distortion","Epistemic inflation","Dissent burial","Classification leak","Audience mismatch","Version overwrite","Recall failure","Recommendation/intelligence mixing"],
[c("normal","Board market brief","limited attention","layered summary/drill-down","CONSUMER_FIT","product released"),c("contradiction","warning urgent, evidence partial","deadline","fact/inference split","EPISTEMIC_LANGUAGE","partial product"),c("attack","request remove caveat","persuasion pressure","block release","DISSENT_SURFACE","RETURN"),c("recovery","claim retracted","50 recipients","recall/ACK/supersede","DISSEMINATION_AUTHORITY","distribution reconciled")]),

sigma_38:s(
"¿Cumple el proceso y artefacto el estándar analítico material—método, lineage, calibration, independence, completeness and hard minima—even si su conclusión parece correcta?","La auditoría de integridad analítica y tradecraft; no la producción del artefacto ni la verdad soberana final.",
["Define quality plan","Audit structural/method fit","Sample provenance/reproducibility","Evaluate calibration/independence","Enforce hard minima","PASS/RETURN/BLOCK with root defect"],
["requirement completeness","method suitability","provenance coverage","reproducibility","source/cognitive independence","contrary evidence","calibration","uncertainty language","dissent visibility","security/authority","termination validity","utility fitness"],
["Freeze artifact/version before review","Derive quality plan from materiality/risk","Check structural completeness and scope","Audit method suitability, assumptions and falsifiers","Sample/replay provenance and calculations risk-weighted","Verify source and cognitive independence separately","Compare confidence language to feature/calibration ceiling","Inspect contrary evidence/dissent/UNKNOWN","Apply nonwaivable hard minima","Locate first invalid node and RETURN; never rewrite product"],
["Reviewer participated in production","Method cannot answer requirement","Material lineage missing","Confidence exceeds calibration ceiling","Dissent omitted","Hard gate waived","Artifact correct by luck but process irreproducible"],
["Style review as QA","Fix artifact for producer","Pass because conclusion plausible","Average gate scores across hard zero","Use reputation as exemption","Declare external audit"],
["AnalyticQualityReport PASS/RETURN/BLOCK","Root defect and reentry condition explicit","Independent verification handoff","Random audit complete","Quality debt registered"],
[
b("All Σ producers","audits process/artifact","own content","FrozenArtifact → QualityReport","Σ38 never coauthors reviewed artifact"),b("Σ36","checks dissent visibility","owns dissent","DissentAudit","quality not decide minority truth"),b("Σ17","samples provenance/replay","owns lineage","AuditBundle","Σ38 not edit edges"),b("Σ16","tests independence claims","owns dependency graph","DependencyAudit","quality not infer sources alone"),b("Σ40","measures internal quality","owns external utility/outcomes","QualityMetrics → EffectivenessReview","quality not utility"),b("Σ01","reports only gate status/root defect","commands department","BlockNotice","Σ1 cannot force PASS"),b("Ω22","submits quality evidence","certifies final Ω standard","CertificationPacket","Σ38 not sovereign certifier"),b("Ω03","exposes audit trail","independent process audit","AuditPacket","Σ38 not external independent"),b("Ω09–12","requests independent verification","replicate/triangulate/fact/epistemic","VerificationAssignment","quality self-check not truth verification"),b("Ω14","exposes attack surface","red team","RedTeamReport","Σ38 not adversarial tribunal"),b("Human auditor","provides review package","external judgment","AuditAcknowledgment","AI cannot label independent audit"),b("Ω24","provides quality trends/proposals","governs change","ChangeProposal","Σ38 not modify standard silently")],
["Reviewer capture","Checklist theater","Hard-gate averaging","Conclusion plausibility bias","Provenance sampling miss","Calibration overclaim","Producer assistance contamination","Quality=utility conflation"],
[c("normal","Review market dossier","complex models","risk-weighted audit","METHOD_SUITABILITY","RETURN one root"),c("contradiction","calculation correct, denominator absent","factually plausible","hard minimum","HARD_MINIMA","FAIL"),c("attack","Σ1 orders pass","deadline","protected refusal","STRUCTURAL_COMPLETENESS","BLOCK"),c("recovery","reviewer coauthored","independence broken","reroute blind review","PROVENANCE_SAMPLE","new report")]),

sigma_39:s(
"¿Cómo preservar exact objective, state, watches, dependencies and unresolved judgments across pauses, migrations and corrections, and recompute from the first invalid node?","La memoria de misión, handover y reconsideration graph; no el juicio nuevo ni el simple transcript.",
["Create durable checkpoint","Transfer active watch","Validate leases/freshness on resume","Open reassessment","Invalidate descendants","Coordinate notification/recompute"],
["objective hash","artifact/version frontier","state/cursor","active leases","pending tool receipts","dependency frontier","watches/triggers","unknowns/dissent","model/tool versions","late events","invalidation set","acknowledgments"],
["Checkpoint objective, graph state and content hashes at safe transitions","Store pointers/structured summaries, not transcript as truth","Record in-flight effects with idempotency receipts","On resume verify versions, leases, clocks and freshness","Reconcile late events by sequence/logical clock","When error found, traverse reverse dependencies","Locate first invalid root and freeze descendants","Recompute minimum affected subgraph","Require re-verification and prior-consumer notification","Close reassessment only after acknowledgments"],
["Objective hash differs without signed delta","Lease/TTL expired","Pending effect lacks receipt","Checkpoint omits dissent/UNKNOWN","Invalidation frontier cannot reach consumer","Resume uses unavailable model as if identical"],
["Copy full chat as memory","Resume from prose summary alone","Re-run irreversible effect","Patch final product","Delete superseded version","Mark notified without ACK"],
["WatchHandover accepted","Mission resumed with validated context","Reassessment closed after reverify/ACK","Mission archived with retention policy","Access/model gap typed BLOCKED"],
[
b("Σ02","receives/returns MissionGraph checkpoint","owns orchestration","CheckpointManifest","Σ39 not schedule mission"),b("All Σ producers","records artifact frontier/triggers","own artifacts","VersionLink","Σ39 not edit judgment"),b("Σ17","uses reverse provenance","owns lineage","DependencyIndex","Σ39 decides invalidation process"),b("Σ33","transfers watch state","owns indicators/warning","WatchHandover","handover not alter threshold"),b("Σ36","transfers unresolved dissent","owns register","DissentFrontier","memory not summarize away"),b("Σ37","triggers recall/notify","owns product/dissemination","RetractionNotice","Σ39 not publish"),b("Σ38","requests revalidation","owns quality","ReviewAssignment","resume not retain old PASS blindly"),b("Σ40","provides frozen baseline/outcome","owns effectiveness","HistoricalRecord","learning not rewrite history"),b("Runtime/StateStore","defines checkpoint contract","persists/migrates","StoreReceipt","store not validate semantics"),b("Ω07","preserves institutional lineage","owns sovereign provenance","ArchiveHandoff","Σ39 not truth commit"),b("Ω24","receives patterns/change data","owns institutional memory/change","PostMissionReview","Σ39 not modify policy"),b("Human owner","receives material correction","acknowledges/decides","CorrectionACK","notification not consent")],
["Checkpoint omission","Transcript-as-truth","Duplicate side effect","Expired lease resume","Late-event misorder","Partial invalidation","Notification failure","Provider-equivalence assumption"],
[c("normal","Weeks-long watch handover","provider change","checkpoint/validate/resume","ACTIVE_WATCH_TRANSFER","no lost state"),c("contradiction","late event predates estimate","sequence conflict","reconcile logical clock","VERSION_LINKAGE","estimate reopens"),c("attack","operator asks overwrite error","hide incident","append/supersede only","ROOT_CAUSE_REPLAY","history preserved"),c("recovery","source retracted","14 descendants","root invalidation/recompute/ACK","NOTIFICATION_PROPAGATION","case closed")]),

sigma_40:s(
"¿Did intelligence improve the authorized decision or warning outcome, at what cost, through which causal path, and what controlled change should be tested without outcome bias or self-modification?","La evaluación ex post de utilidad/efectividad y propuesta de aprendizaje; no el despliegue de cambios ni la reescritura de predictions.",
["Freeze ex-ante record","Define outcome/use metrics","Separate truth, timeliness, utility","Analyze confounders/attribution","Evaluate cost/latency","Propose controlled change to Ω24"],
["frozen intelligence artifact","intended use","actual use/disposition","resolved outcome","accuracy/calibration","timeliness","decision counterfactual","confounders","cost/latency","dissent quality","harm/benefit","change hypothesis"],
["Freeze forecast/product/decision model before outcome review","Predefine accuracy, timeliness, use and utility separately","Collect actual use/ACK and decision path","Resolve outcome with independent labels","Compare forecast calibration without hindsight edits","Analyze whether intelligence changed action versus merely coincided","Control task mix, exogenous events and implementation quality","Attribute failures to requirement/collection/analysis/product/use nodes","Assess marginal value and opportunity cost","Propose change with test, shadow, rollback and approval; never deploy"],
["Outcome label ambiguous/manipulated","Decision did not consume product","Success caused by external factor","Task mix differs from comparison cohort","Metric rewards overwarning/volume","Change proposal lacks causal mechanism"],
["Outcome good=analysis good","Blame analyst for ignored warning","Optimize satisfaction","Use reputation as authority","Modify prompts/policy silently","Delete failed forecasts"],
["IntelligenceEffectivenessReview complete","Outcome unresolved and review deferred","ChangeExperimentProposal handed Ω24","No causal attribution possible—UNKNOWN","Monitoring window complete"],
[
b("Σ05","uses frozen intended decision/use","owns ex-ante consumer model","ConsumerDecisionModel","Σ40 not redefine success"),b("Σ32/33","scores frozen estimates/warnings","own production","ResolvedRecord","Σ40 not edit originals"),b("Σ37","measures delivery/ACK/use","owns product/dissemination","DistributionLedger","delivery not utility"),b("Σ38","receives process quality","owns internal tradecraft","QualityReport","quality not outcome utility"),b("Σ39","uses immutable history/version links","owns continuity","HistoricalBundle","Σ40 not rewrite memory"),b("Σ01","reports portfolio findings","commands department","EffectivenessBrief","Σ1 not suppress bad metrics"),b("Ω24","proposes changes","tests/approves institutional evolution","ChangeExperimentProposal","Σ40 MODIFY_POLICY=X"),b("Ω20","provides cost/value evidence","allocates resources","ResourceReview","Σ40 not reprioritize sovereignly"),b("Ω03/22","provides outcomes/audit evidence","audit/certify quality","AuditPacket","internal review not independent audit"),b("Human consumer","collects use/consequence feedback","owns decision","OutcomeInterview","satisfaction not truth"),b("Operations","collects implementation telemetry","owns execution","OutcomeTelemetry","bad execution not intelligence error automatically"),b("External evaluator","submits frozen data","independently evaluates","EvaluationPackage","Σ40 cannot call itself external")],
["Outcome bias","Hindsight rewrite","Attribution overclaim","Survivorship bias","Task-mix confounding","Goodhart metrics","Reputation substitution","Silent self-modification"],
[c("normal","Evaluate warning portfolio","outcomes resolved","calibration/use/cost separated","METRIC_PREREGISTRATION","EffectivenessReview"),c("contradiction","accurate product unused","decision failed","separate truth vs utility","TRUTH_UTILITY_SEPARATION","product/dissemination issue"),c("attack","leader blames analyst","implementation ignored alert","frozen ACK/decision path","CONFOUNDER_ANALYSIS","attribution bounded"),c("recovery","metric drove alert spam","Goodhart","propose shadow metric change","CHANGE_AUTHORITY","Ω24 approval required")])
};
