import{spec as s,boundary as b,scenario as c}from"./spec-helper.mjs";
export default {
sigma_21:s(
"¿Las cifras y categorías comparadas miden el mismo constructo, población, unidad, periodo y proceso de observación con error conocido?","El sistema de medición y comparabilidad; no el valor estratégico de la cifra.",
["Definir construct/operationalization","Auditar sampling frame/missingness","Normalizar units/currency/time","Evaluar comparability/regime breaks","Reproducir calculations","Fijar precision ceiling"],
["construct definition","operational measure","unit/scale","population/denominator","sampling frame","missingness mechanism","measurement error","transformation chain","method version","comparability class","uncertainty propagation"],
["Separar construct conceptual de variable observada","Documentar población, denominator, inclusion/exclusion y sampling process","Clasificar missingness MCAR/MAR/MNAR o mecanismo específico","Normalizar units/currency/inflation con transform explícito","Propagar error y covariance por cada cálculo","Detectar method breaks y segmentar regimes","Construir comparability matrix, no una bandera binaria","Reproducir cálculo desde raw snapshot/code","Redondear output al resolution ceiling","Emitir sensitivity a assumptions/metodología"],
["Métrica cambia definición entre periodos","Denominator desconocido o móvil","Missingness correlaciona con target","Normalización domina efecto observado","Error interval cruza decision threshold","Series comparten nombre pero no construct"],
["Promediar porcentajes con denominadores distintos","Comparar revenue bruto/neto","Imputar missing como cero","Mostrar decimales no soportados","Backfill silencioso","Usar correlation de métricas como validity"],
["MeasurementAssessment con comparability class","Incomparabilidad material declarada","Reproducibilidad dentro de tolerancia","Precision ceiling aplicado","Nuevos datos no cambian decision interval"],
[
b("Σ03","define variables requeridas","posee intelligence question","MeasurementDefinition","Σ21 no cambia decision need"),b("Σ08","recibe raw tables/definitions","autentica records","PrimaryRecordCorpus","Σ21 no autentica issuer"),b("Σ10/Σ11","recibe sensor/error metadata","poseen collection","MeasurementChain","Σ21 no opera sensores"),b("Σ17","entrega transform/code receipts","posee provenance","CalculationLineage","reproducible no implica valid"),b("Σ19","recibe time regimes","posee chronology","MethodInterval","Σ21 no reordena events"),b("Σ22","define construct ontology","gobierna concepts","ConceptDefinition","Σ21 no edita ontology sola"),b("Σ24","entrega comparable measures","fusiona evidence","MeasurementAssessment","fusion no mezcla incomparable"),b("Σ27","provee measurement validity","analiza causalidad","MeasurementModel","good measurement no identifica cause"),b("Σ31/Σ32","entrega baseline/error","anomaly/estimate","QuantitativeInput","Σ21 no detecta/forecast"),b("Data","especifica transformations/tests","ejecuta pipelines","DataWorkOrder","pipeline no decide semantics"),b("Ω11","entrega quantitative claim components","fact-checks","ClaimAudit","cálculo correcto puede usar premise falsa"),b("Σ38","entrega reproducibility sample","audita method","QualityReport","Σ21 no autocertifica")],
["Construct drift","Denominator mismatch","MNAR blindness","Unit/currency error","False precision","Regime-break smoothing","Transformation bug","Covariance omission"],
[c("normal","Comparar mercado entre países","monedas/definitions distintas","comparability matrix y PPP/sensitivity","COMPARABILITY","rango comparable limitado"),c("contradicción","dos datasets dan tasas opuestas","denominators diferentes","reconstruye populations","CONSTRUCT_DEFINITION","contradicción explicada"),c("ataque","vendor entrega score propietario","sin metodología","limita uso y exige validation","REPRODUCIBLE_CALCULATION","no acepta score como fact"),c("recuperación","ETL duplicó filas","estimate downstream","corrige transform y propaga uncertainty","UNIT_NORMALIZATION","descendientes recalculados")]),

sigma_22:s(
"¿Qué significan institucionalmente las entidades, conceptos y relaciones, y cómo evoluciona ese significado sin romper consultas, memoria ni comparabilidad histórica?","La ontología y knowledge graph schema; no los hechos de instancia ni la narrativa analítica.",
["Definir concepts/relations/constraints","Gestionar synonym/homonym","Proponer ontology delta","Migrar datos/queries","Preservar raw terms","Bloquear semantic collision"],
["concept identifier","definition/intension","extension criteria","edge type semantics","cardinality/constraints","synonym set","context/jurisdiction","ontology version","migration mapping","query impact","raw-term preservation"],
["Registrar competency questions antes de modelar","Definir concepto con inclusión/exclusión y counterexamples","Separar synonym, near-synonym y homonym","Tipar relations con direction, domain/range y temporal semantics","Probar constraints contra fixtures positivos/negativos","Vincular raw term a normalized concept sin destruirlo","Analizar ontology delta y downstream query impact","Diseñar reversible migration/dual-read","Ejecutar regression queries antes de commit","Versionar y notificar semantic change"],
["Concepto no responde competency question","Dos términos iguales tienen extensión distinta","Edge type mezcla ownership/influence","Migration pierde raw term","Query results cambian sin expected delta","Definition codifica una hipótesis como hecho"],
["Crear concepto por cada palabra","Fusionar sinónimos por embedding solo","Cambiar schema in-place","Usar ontology para rellenar missing facts","Confundir type con instance","Ocultar semantic debt"],
["KnowledgeGraphDelta validado y reversible","Competency queries pasan","Semantic conflict permanece typed","Migration/rollback probado","No downstream consumer sin acknowledgment"],
[
b("Σ18","define types/identifier constraints","resuelve instances","EntityTypeContract","ontology no decide identity"),b("Σ20","define edge semantics","analiza graph instances","EdgeTypeContract","schema no crea relation"),b("Σ23","recibe cultural/linguistic distinctions","posee interpretation","SemanticContextAssessment","ontology no borra context"),b("Σ21","define measure concepts","posee comparability","ConstructDefinition","same label no means same measure"),b("Σ24","entrega normalized schema","fusiona evidence","KGVersionRef","fusion no edita ontology"),b("Σ25/Σ26","modelan actors/systems","usan concepts","DomainModelContract","analytic model not ontology truth"),b("Σ17","provee delta/migration lineage","custodia provenance","OntologyTransformReceipt","versioning not semantic validation"),b("Σ39","notifica consumers/reconsideration","posee continuity","SemanticChangeEvent","Σ22 no decide blast policy"),b("Data","solicita migration/query tests","ejecuta graph store","DataWorkOrder","store schema not institution meaning"),b("Documentation","publica glossary","gestiona representation","PublicationReceipt","glossary follows canonical ontology"),b("Ω12","alinea epistemic labels","gobierna knowledge language","EpistemicOntologyReview","Σ22 no redefine VERIFIED"),b("Σ38","entrega query regression","audita completeness","QualityReport","Σ22 no autocertifica")],
["Ontology drift","Homonym collapse","Relation-type conflation","Irreversible migration","Query regression","Hypothesis-as-schema","Raw-term loss","Schema proliferation"],
[c("normal","Unificar conceptos de capacidad","cinco departamentos usan términos distintos","competency questions y mappings","CONCEPT_DEFINITION","delta reversible"),c("contradicción","cliente significa buyer y end-user","datasets mezclan","separa concepts/context","EDGE_TYPING","queries corregidas"),c("ataque","analista añade 'adversario' como type factual","hipótesis embebida","rechaza delta","DEPENDENCY_INTEGRITY","ontology neutral"),c("recuperación","migration cambió resultados","query de warning afectada","rollback/dual-read y notify","QUERY_REGRESSION","warning revalidado")]),

sigma_23:s(
"¿Qué significa realmente una expresión, símbolo o conducta dentro de su idioma, registro, cultura, periodo y audiencia, y qué ambigüedades sobreviven?","El contexto lingüístico-cultural-semántico; no la intención psicológica ni el hecho externo.",
["Preservar original/translations","Mapear ambiguity set","Determinar register/audience/context","Analizar cultural evidence","Detectar semantic drift","Emitir interpretation alternatives"],
["original token/span","language/dialect","register","speaker/audience","historical period","literal/pragmatic meaning","ambiguity candidates","translation confidence","cultural convention evidence","semantic drift","code-switching"],
["Preservar texto/audio original con locator","Identificar idioma, dialecto, register y code-switching","Generar traducciones independientes para material","Separar literal, idiomatic, pragmatic y institutional meaning","Construir ambiguity set antes de elegir reading","Usar corpus/context evidence, no estereotipo","Modelar speaker/audience relationship","Comparar historical meanings y semantic drift","Registrar untranslatable residue","Entregar alternatives y discriminants"],
["Traducciones independientes divergen materialmente","Meaning depende de contexto ausente","Cultural claim se basa en estereotipo","Term cambió en periodo relevante","Irony/code no resoluble","Analista conoce conclusión preferida antes de traducir"],
["Una traducción definitiva","Back-translate como única verificación","Inferir intención desde idiom","Universalizar norma cultural","Borrar término original","Usar LLM fluency como expertise evidence"],
["SemanticContextAssessment con alternatives","Ambiguity no material para decisión","UNTRANSLATABLE/CONTEXT_MISSING","Independent translation complete","New context no cambia interpretation"],
[
b("Σ08","recibe original snapshot","autentica record","OriginalSpanLocator","Σ23 no certifica issuer"),b("Σ09","interpreta transcript/context","posee elicitation","BilingualTranscript","interpreter no conduce testimony sin separation"),b("Σ22","propone concept mappings","gobierna ontology","SemanticDeltaProposal","Σ23 no commit ontology"),b("Σ19","usa historical interval","posee chronology","SemanticPeriod","meaning today not meaning then"),b("Σ25","entrega behavior statement meaning","modela actor intent","InterpretationSet","semantic nuance not intent proof"),b("Σ29","entrega influence narrative meaning","analiza deception","NarrativeSemantics","coded language not sponsor attribution"),b("Σ24","entrega alternatives","fusiona evidence","SemanticContextAssessment","fusion cannot select hidden interpretation"),b("Σ36","preserva minority translation","posee dissent","AlternativeReading","majority vote not semantics"),b("Σ37","adapta product language","posee dissemination","AudienceLanguageContract","product simplification preserves ambiguity"),b("External translators","emite blind commissions","ejecutan translation","SpecialistArtifact","translator gets minimum context"),b("Ω11","atomiza linguistic claims","fact-checks","ClaimAudit","meaning judgment labeled inference"),b("Σ38","entrega translation independence test","audita method","QualityReport","Σ23 no autocertifica")],
["Translation anchoring","Cultural stereotyping","Register blindness","Semantic drift","Original-text loss","Context leakage","Irony/code misread","False consensus among same-model translators"],
[c("normal","Interpretar statement rival","dialecto técnico","dos traducciones y register analysis","TRANSLATION_INDEPENDENCE","dos readings con discriminants"),c("contradicción","literal amenaza; idiom benigno","audience context incompleto","preserva ambiguity","AMBIGUITY_SET","intent no afirmada"),c("ataque","sponsor entrega traducción preferida","anchoring","blind route sin esa versión","ORIGINAL_PRESERVED","resultado independiente"),c("recuperación","term histórico malinterpretado","actor assessment contaminado","corrige semantic period y propaga","SEMANTIC_DRIFT","claims reabiertos")]),

sigma_24:s(
"¿Qué conjunto integrado de findings emerge de streams admisibles después de ajustar calidad, dependencia, contradicción y sensibilidad sin promediar desacuerdos?","La fusión all-source a nivel de claim; no la certificación soberana ni la fabricación de consenso.",
["Normalizar claim atoms","Integrar support/contrary evidence","Aplicar dependency adjustment","Preservar contradictions/dissent","Ejecutar sensitivity","Emitir fused findings y gaps"],
["atomic claim","evidence support/contrary","source quality vector","effective support clusters","method independence","freshness","contradiction state","sensitivity to source removal","dissent materiality","epistemic status","residual gap"],
["Aceptar sólo admitted/provenance-linked inputs","Atomizar findings en claims compatibles/incompatibles","Separar evidence quality, independence y relevance","Construir evidence matrix por claim","Aplicar source dependency clusters antes de aggregation","No reducir contradicción a average; abrir case","Ejecutar leave-one-cluster-out sensitivity","Mantener findings alternativos/minority","Asignar epistemic state bajo ceiling","Emitir gaps y downstream verification needs"],
["Finding depende de un cluster único","Claims comparados tienen scope distinto","Contradiction material no está resuelta","Sensitivity cruza decision threshold","Measurement/semantic mismatch","Producer route contamina reviewer"],
["Promedio de probabilidades heterogéneas","Mayoría de fuentes","Ocultar dissent en appendix","Usar reputación como weight automático","Fusionar antes de admissibility","Escribir narrative primero y buscar support"],
["AllSourceFusion con claims/gaps completos","Material contradictions owned","Sensitivity stable o visible","No additional stream changes decision","Input retraction triggers freeze"],
[
b("Σ14","consume admitted objects","decide admissibility","AdmissionManifest","fusion no bypass quarantine"),b("Σ15","consume source vectors","evalúa source","SourceAssessment","fusion no re-score motive"),b("Σ16","consume effective clusters","mapea dependencies","DependencyGraph version","raw count prohibited"),b("Σ17","consume lineage","custodia provenance","ProvenanceBundle","fusion not truth certification"),b("Σ18–Σ23","consume structured findings","resolve entity/time/network/measure/semantics","TypedArtifacts","fusion no usurpa disciplines"),b("Σ28","entrega fusion matrix","posee hypothesis portfolio","AllSourceFusion → HypothesisSet","fusion no elige final hypothesis"),b("Σ32","entrega fused features","commit estimate","EstimateInput","fusion no asigna probability"),b("Σ36","entrega contradictions","owns dissent","DissentRegisterDelta","fusion cannot erase minority"),b("Σ37","entrega findings","diseña product","ProductInputManifest","fusion not audience narrative"),b("Σ38","entrega sensitivity/audit","audita method","QualityReport","producer not sole certifier"),b("Ω10/11/12","entrega candidate findings","verify/fact-check/epistemic language","VerificationPacket","Σ24 no certifies"),b("Σ39","recibe dependency triggers","reconsideration","FusionVersionLink","retraction propagates")],
["False consensus","Scope-mismatch merge","Contradiction averaging","Dependency undercount","Single-cluster dominance","Dissent burial","Narrative-first fusion","Stale-input carryover"],
[c("normal","Fusionar mercado opaco","records, experts, telemetry","claim matrix y leave-one-out","DEPENDENCY_ADJUSTMENT","range con residual gap"),c("contradicción","dos methods divergen","measurement scopes differ","mantiene findings separados","CONTRADICTION_VISIBILITY","no average"),c("ataque","20 routes same source","consensus aparente","collapse y confidence ceiling","INDEPENDENCE","quorum fail"),c("recuperación","source retracted","finding central","freeze descendants y re-fuse","SENSITIVITY","product superseded")]),

sigma_25:s(
"¿Qué puede hacer un actor, qué intenta hacer, qué restricciones enfrenta y qué observaciones discriminarían entre intenciones alternativas?","El actor model capability–intent–constraints; no la identidad, moralidad ni estrategia soberana.",
["Assess capabilities/readiness","Generate intent hypotheses","Map constraints/incentives","Separate words/behavior","Derive observable predictions","Update actor model"],
["capability inventory","readiness/deployability","intent hypotheses","preference ordering","constraints","incentives/costs","behavior statements gap","observable predictions","deception incentive","adaptation capacity"],
["Separar capacidad nominal, disponible y desplegable","Modelar readiness y bottlenecks","Generar intenciones competidoras incluida inercia/oportunismo","Distinguir declaratory policy de revealed behavior","Mapear legal, resource, organizational y temporal constraints","Derivar predictions diferenciadas por intent","Buscar costly signals y actions under constraint","Actualizar con behavior, no retórica sola","Mantener mirror-imaging check","Emitir capability/intent confidence separado"],
["Capability no es deployable en horizon","Mismo behavior compatible con varias intents","Constraint desconocida domina acción","Prediction no discrimina","Actor puede estar deceiving","Analyst preference model sustituye actor preferences"],
["Tiene capacidad, por tanto lo hará","Declaró intención, por tanto es verdad","No actuó, por tanto no quería","Psicologizar sin observables","Mirror imaging","Confundir constraint con preference"],
["ActorAssessment con predictions y constraints","Intent remains unresolved but decision-bounded","Capability change trigger registered","New behavior no changes ranking","Identity/chronology uncertainty blocks"],
[
b("Σ18","consume resolved actor identity","resuelve entity","EntityResolutionCase","actor model no decide identity"),b("Σ19","consume behavior chronology","owns temporal truth","EventChronology","order precedes intent inference"),b("Σ20","consume network/resources","models structure","NetworkAssessment","network position not intent"),b("Σ23","consume statements meaning","owns semantics","SemanticContextAssessment","phrase not intent"),b("Σ26","provides actor within system","models environment","ActorAssessment","Σ25 not full system"),b("Σ27","provides mechanism hypotheses","analyzes causality","ActorMechanismInput","intent not cause by assertion"),b("Σ28","generates competing intents","owns structured hypotheses","IntentHypothesisSet","Σ25 provides domain model"),b("Σ29","provides deception incentive/signals","analyzes deception","DeceptionAssessment","Σ25 not attribute campaign"),b("Σ32/33","provides actor features/signposts","estimate/warning","ActorIndicators","Σ25 not forecast/alert"),b("Strategy/Ω17","delivers actor reality","designs strategy","StrategicRealityBrief","Σ25 not choose response"),b("Ω11","atomizes intent claims","fact-checks facts","ClaimAudit","intent labeled inference"),b("Σ38","provides mirror/adversarial review","audits tradecraft","QualityReport","Σ25 not self-certify")],
["Capability=intent fallacy","Readiness overclaim","Mirror imaging","Statement-behavior conflation","Constraint omission","Intent monoculture","Costly-signal misread","Adaptive actor staleness"],
[c("normal","Competitor expansion","capacity announced","tests deployability/constraints","CAPABILITY_READINESS","capability high, intent moderate"),c("contradicción","rhetoric aggressive; investment low","multiple intents","prediction table","BEHAVIOR_STATEMENT_GAP","dissent preserved"),c("ataque","deceptive actor plants costly signal","signal can be staged","orthogonal constraints check","OBSERVABLE_PREDICTIONS","intent ceiling"),c("recuperación","new bottleneck emerges","forecast assumed readiness","update constraints/invalidate","CONSTRAINT_MAP","estimate reopens")]),

sigma_26:s(
"¿Qué system boundary, stocks, flows, feedbacks, delays and regimes shape the strategic environment, and where can local analysis fail under system change?","El modelo sistémico/contextual y régimen; no la causal claim identificada ni la estrategia.",
["Define system boundary","Map stocks/flows/feedbacks","Identify delays/nonlinearities","Model regimes/exogenous drivers","Generate alternative framings","Expose boundary sensitivity"],
["system boundary","stocks/flows","feedback polarity","delay distribution","constraints/capacities","exogenous drivers","regime state","nonlinearity/threshold","cross-domain coupling","boundary sensitivity","model purpose"],
["Define model purpose before boundary","Map stocks/flows with dimensional consistency","Identify reinforcing/balancing feedback and evidence","Represent delays explicitly","Separate endogenous/exogenous variables provisionally","Locate capacity constraints and thresholds","Construct alternative boundaries/framings","Test regime shifts and structural breaks","Trace cross-domain second/third-order pathways","Emit assumptions and leverage hypotheses, not strategy"],
["Boundary excludes material feedback","Stock-flow equations violate units","Feedback direction lacks evidence","Delay uncertainty changes conclusion","Regime switch invalidates parameters","Alternative framing reverses implication"],
["Causal-loop art as evidence","Everything connected to everything","Treat model as prediction","Hide boundary choice","Assume equilibrium","Recommend intervention without causal/strategy owners"],
["StrategicEnvironmentModel fit for decision purpose","Boundary sensitivity explicit","Regime UNKNOWN with scenarios","New coupling marginal","Model superseded by regime event"],
[
b("Σ25","embeds actor in environment","models actor","ActorAssessment","system doesn't erase agency"),b("Σ20","consumes network structure","models graph","NetworkAssessment","network not full dynamics"),b("Σ21","uses dimensional measures","owns measurement","MeasurementAssessment","systems model not normalize data"),b("Σ27","supplies causal candidates/context","tests mechanisms","EnvironmentModel → DAG","Σ26 not certify causality"),b("Σ28","provides alternative framings","owns hypotheses","FramingSet","system boundary not preferred hypothesis"),b("Σ32","provides scenario structure","estimates outcomes","ModelInput","systems model not forecast"),b("Σ34","provides regime/tail surfaces","searches surprise","BoundaryChallenge","Σ26 not tail hunter alone"),b("Σ18","receives cross-domain pathways","evaluates impacts Ω role","ImpactInput","Σ26 not decide impact acceptance"),b("Strategy/Ω17","delivers constraints/leverage hypotheses","designs strategy","StrategicEnvironmentModel","Σ26 not choose leverage"),b("Simulation/Ω16","delivers formal model spec","simulates","SimulationCommission","Σ26 not confuse simulation with truth"),b("Ω13/14","provides assumptions/attack surface","challenge/red-team","ChallengePacket","Σ26 not self-challenge only"),b("Σ38","delivers model audit","audits method","QualityReport","Σ26 not certify model")],
["Boundary blindness","Stock-flow inconsistency","Feedback storytelling","Delay omission","Regime-lock","Cross-domain coupling omission","Equilibrium assumption","Model-as-reality"],
[c("normal","Supply-chain resilience","multi-tier delays","stocks/flows and feedbacks","STOCK_FLOW_RULES","environment model"),c("contradicción","local data improves while system worsens","boundary issue","expand boundary and alternative framing","BOUNDARY_DEFINITION","implication changes"),c("ataque","sponsor wants simple causal loop","complexity suppressed","refuse unsupported arrows","FEEDBACK_EVIDENCE","partial model"),c("recuperación","regulation creates regime shift","parameters stale","supersede regime and reopen estimates","REGIME_ASSUMPTIONS","downstream notified")]),

sigma_27:s(
"¿Qué causal mechanisms could generate the observed pattern, which are identifiable from available/obtainable evidence, and where do transportability assumptions break?","El causal question, competing DAGs y mechanism assessment; no la prediction sola ni la intervention decision.",
["Formalize causal estimand","Build competing DAGs","Assess identifiability","Evaluate study/design validity","Test mechanisms","Bound transportability"],
["treatment/exposure","outcome","estimand/population","confounders","mediators/colliders","selection mechanism","temporal order","identification assumptions","mechanism evidence","heterogeneity","transport target"],
["Define causal estimand, population and counterfactual","Build competing DAGs including reverse/common cause","Use chronology to remove impossible edges","Identify backdoor/frontdoor/instrument or declare nonidentifiable","Prevent collider/selection conditioning","Assess design: experiment, quasi, observational, process tracing","Seek mechanism evidence and negative controls","Estimate sensitivity to unmeasured confounding","Model heterogeneity/regime interaction","State transportability limits and intervention difference"],
["No identification set under plausible DAGs","Reverse causation remains","Unmeasured confounder can explain effect","Mechanism evidence contradicts statistical association","Target regime differs materially","Observed intervention is not proposed intervention"],
["Correlation=causation","Temporal precedence=causation","Control every variable","Causal language from predictive model","Ignore selection/collider","Transport effect without mechanism"],
["CausalMechanismAssessment with identified/bounded result","NONIDENTIFIABLE typed","Mechanism hypotheses discriminated","Transport ceiling accepted","New evidence marginal"],
[
b("Σ19","consumes temporal constraints","owns chronology","EventChronology","precedence not sufficient"),b("Σ21","consumes valid measures","owns measurement","MeasurementAssessment","precision not identification"),b("Σ26","consumes system/context/regime","owns environment","EnvironmentModel","context not causal proof"),b("Σ28","constructs competing DAG hypotheses","owns hypothesis method","CausalHypothesisSet","Σ27 assesses causality"),b("Σ31","receives patterns/anomalies","detects signals","AnomalyPortfolio","pattern not cause"),b("Σ32","provides causal features/limits","estimates forecasts","MechanismAssessment","causal estimate not forecast automatically"),b("Σ16","adjusts evidence dependencies","owns source graph","DependencyGraph","multiple studies may share data"),b("Research/Data","specifies design/analysis","execute study","ResearchCommission/DataWorkOrder","Σ27 not fabricate experiment"),b("Simulation/Ω16","supplies causal structure","simulates scenarios","SimulationModel","simulation not identification"),b("Strategy/Ω17","supplies intervention assumptions","chooses strategy","CausalAssessment","Σ27 not recommend alone"),b("Ω08","delivers causal candidate","context/causality oversight","VerificationPacket","Σ27 not sovereign certify"),b("Σ38","provides design/reproducibility audit","audits tradecraft","QualityReport","Σ27 not self-certify")],
["Confounding","Reverse causation","Collider conditioning","Selection bias","Mechanism mismatch","Transport failure","Estimand drift","Causal-language inflation"],
[c("normal","Does price cut cause retention","observational data","DAG/sensitivity/negative control","IDENTIFIABILITY","bounded effect"),c("contradicción","association positive; mechanism negative","selection suspected","competing DAGs","COMPETING_DAGS","nonidentified"),c("ataque","sponsor asks causal wording","only prediction model","refuse causal claim","CAUSAL_QUERY","predictive label"),c("recuperación","new regime breaks transport","strategy depended","recompute target assumptions","TRANSPORTABILITY","decision reopens")]),

sigma_28:s(
"¿Qué mutually distinct hypotheses—including null and uncomfortable alternatives—explain the evidence, what each predicts, and which discriminants can actually separate them?","El portfolio de hipótesis competidoras y structured analysis; no el estimate commit.",
["Generate hypothesis set","Ensure distinct/null inclusion","Build evidence-prediction matrix","Assess diagnosticity","Commission disconfirmation","Maintain blind routes"],
["hypothesis statement","scope","prior basis","predicted observations","forbidden observations","diagnosticity","evidence dependence","assumptions","disconfirmation search","blind-route independence","residual alternatives"],
["Frame question before seeing favored answer","Generate independent and forced-contrarian hypotheses","Include null/error/deception/regime alternatives","Make hypotheses mutually distinguishable in scope","Predeclare expected/forbidden observations","Score evidence diagnosticity, not consistency count","Adjust for dependencies and missingness","Search actively for disconfirming evidence","Run blind analyst route with different method/context","Preserve unresolved alternatives and minority report"],
["Hypotheses make same predictions","Null omitted","Evidence was used to create and test without disclosure","One cluster supports all discriminants","Contrary evidence unexplained","Blind route contaminated"],
["Token alternatives","Strawman null","Scorecard arithmetic as truth","Eliminate hypothesis on absent low-detection evidence","Converge by vote","Reveal preferred hypothesis to blind route"],
["AnalyticHypothesisSet covers material space","Discriminants executed or gap explicit","One hypothesis dominates robustly or alternatives remain","Decision no longer sensitive","New hypothesis trigger registered"],
[
b("Σ03","consumes discriminating requirements","owns questions","RequirementSet","Σ28 not rewrite objective"),b("Σ24","consumes fused evidence","owns fusion","AllSourceFusion","hypothesis method not re-fuse"),b("Σ27","constructs causal hypotheses jointly","assesses causality","CompetingDAGs","Σ28 not identify effects"),b("Σ29","includes deception alternatives","analyzes deception","DeceptionHypothesis","not every surprise deception"),b("Σ31","consumes anomalies","owns pattern validation","AnomalyPortfolio","anomaly not hypothesis proof"),b("Σ32","delivers hypothesis portfolio","commits probabilities/estimate","HypothesisSet","Σ28 not probability owner"),b("Σ34","receives edge hypotheses","searches surprise","AlternativeMechanisms","Σ28 not exhaustive unknowns"),b("Σ36","preserves minority","owns dissent","DissentRegister","hypothesis elimination requires rationale"),b("Σ09/Research","issues blind discriminant tasks","collect/execute","BlindCommission","minimum context"),b("Ω13/14/15","delivers assumptions/alternatives","challenge/red team/reframe","ChallengePacket","Σ28 not replace Ω adversarial"),b("Ω09","defines independent replication","replicates","BlindRouteManifest","same prompt/model not independent"),b("Σ38","provides structured-method audit","audits","QualityReport","Σ28 not self-certify")],
["Premature convergence","Null omission","Hypothesis duplication","Evidence double-use","Diagnosticity inflation","Blind-route contamination","Strawman alternative","Vote-as-truth"],
[c("normal","Why competitor delays launch","ambiguous signals","five hypotheses + predictions","HYPOTHESIS_DISTINCTNESS","portfolio discriminable"),c("contradicción","evidence supports two hypotheses","shared prediction","seek hard discriminant","DIAGNOSTICITY","both remain"),c("ataque","leader orders favorite hypothesis","authority pressure","blind contrarian route","BLIND_INDEPENDENCE","dissent protected"),c("recuperación","null omitted","estimate overconfident","add null/recompute matrix","NULL_INCLUSION","estimate reopened")]),

sigma_29:s(
"¿Existe una deliberate effort to shape our belief by controlling observables, or do error, selection, incentives and benign coordination explain the pattern better?","La hipótesis de deception/denial/influence y sus hard-to-fake discriminants; no la counterintelligence interna ni la atribución ofensiva.",
["Define target belief/deceiver objective","Map observable control","Compare deception/error/benign alternatives","Design hard-to-fake discriminants","Protect collection strategy","Estimate residual deception risk"],
["target belief","potential deceiver benefit","capability/access to observables","channel control","coordination evidence","costly/hard-to-fake signal","benign alternatives","denial/spoofing pattern","attribution uncertainty","residual deception risk"],
["State exactly what belief would be manipulated","Model who benefits without inferring sponsor","Map which observables actor can control","Separate deception, ordinary error, selection and emergent coordination","Identify anomalies and unique fabrication costs","Design discriminants difficult to anticipate/fake","Route collection orthogonally and conceal discriminants","Test whether deception hypothesis predicts failures","Keep operation attribution separate","Bound residual risk in downstream findings"],
["Actor lacks capability/access","Benign mechanism predicts same pattern","Coordination evidence has shared-platform cause","Discriminant was exposed before collection","Attribution relies on motive only","Deception hypothesis becomes unfalsifiable"],
["Wrong therefore deceptive","Coordination therefore centralized","Suspicion as censorship","Publish discriminants to target","Attribute sponsor without evidence","Make every counterevidence part of conspiracy"],
["DeceptionAssessment discriminates alternatives","Residual risk explicit","Operational safety requires protected collection","Attribution remains UNKNOWN","No new discriminant positive VOI"],
[
b("Σ15","consumes source motive/capability","owns source model","SourceAssessment","motive not deception proof"),b("Σ16","consumes coordination/dependency","owns source graph","DependencyGraph","common origin not sponsor"),b("Σ25","consumes actor capability/incentives","owns actor model","ActorAssessment","capability not action"),b("Σ28","provides deception hypothesis","owns portfolio","HypothesisSet","Σ29 tests, not monopolizes alternatives"),b("Σ30","analyzes external deception","owns internal compromise","Deception/CI separation","target operation not institution compromise"),b("Σ31","consumes anomalies","owns validation","AnomalyPortfolio","anomaly not deception"),b("Σ06/12","designs protected collection feedback","own portfolio/gaps","OrthogonalTasking","Σ29 not reveal discriminants"),b("Σ33","provides spoofing risk","owns warning","WarningInput","Σ29 not suppress alert alone"),b("Ω14","delivers attack evidence","red-teams system","RedTeamReport","Σ29 not institutional red team"),b("Ω15","delivers alternatives","reframes","AlternativePacket","deception not only third option"),b("Security/Legal","requests defensive controls","execute/authorize","ExchangePacket","Σ29 not offensive influence"),b("Σ38","delivers paranoia/attribution audit","audits","QualityReport","Σ29 not self-certify")],
["Deception paranoia","Intent overclaim","Coordination attribution","Discriminant leak","Benign alternative omission","Narrative censorship","Motive conflation","Unfalsifiable conspiracy"],
[c("normal","Coordinated narrative","shared errors","maps target belief/control","BENIGN_ALTERNATIVES","manipulation likely, sponsor unknown"),c("contradiction","authentic docs selectively released","truthful fragments mislead","models selection deception","TARGET_BELIEF","content true, narrative risk"),c("attack","analyst labels criticism disinformation","institutional convenience","forces benign/independent route","RESIDUAL_RISK","censorship blocked"),c("recovery","discriminant leaked","target adapts","retire indicator and redesign route","OPERATIONAL_SAFETY","warning model revised")]),

sigma_30:s(
"¿Ha sido comprometida la institución, una fuente, herramienta, contexto o ruta analítica; cuál es el blast radius y cómo se contiene sin destruir evidencia ni independencia?","El CounterintelligenceCase interno y contamination response; no el análisis de propaganda externa ni la disciplina laboral arbitraria.",
["Open protected CI case","Triage compromise indicators","Preserve evidence","Contain least-disruptively","Trace blast radius","Revalidate affected outputs"],
["compromise indicator","asset/source/tool/context","access path","time window","evidence integrity","affected instances/artifacts","blast radius","alternative causes","containment cost","investigator independence","recovery proof"],
["Accept protected report without administrative suppression","Separate anomaly, error, policy violation and compromise hypotheses","Freeze volatile evidence and audit sequence","Appoint investigator independent of implicated route","Map access paths, credentials, prompts, tools and outputs","Apply least-disruptive containment proportional to evidence","Compute transitive blast radius through context/provenance graphs","Rotate/revoke only affected capabilities","Re-run from clean root with blind comparison","Close only with recovery proof and residual monitoring"],
["Investigator reports to implicated owner","Evidence chain altered during containment","Alternative benign causes not tested","Blast radius excludes shared context/model","Containment destroys source or mission unnecessarily","Clean replay reproduces anomaly"],
["Accuse on suspicion","Use CI to silence dissent","Unauthorized surveillance","Confront source before preservation","Delete compromised artifacts","Declare clean because malware scan passes"],
["CounterintelligenceCase resolved/contained","Residual risk accepted by authority","Affected outputs revalidated/retracted","Case transferred to Security/Legal","Evidence insufficient remains SUSPENDED not exonerated/convicted"],
[
b("Σ29","receives external deception indicators","analyzes external influence","ProtectedSignal","Σ30 not attribute narrative"),b("Σ13","uses protected identity/compartments","owns handling","SealedCaseAccess","CI not expose sources"),b("Σ14","receives exploit/quarantine signals","owns intake","MaliciousInputSignal","intake anomaly not compromise proof"),b("Σ15","receives source behavior change","owns source assessment","SourceCompromiseSignal","Σ30 investigates institution/channel"),b("Σ17","uses forensic lineage","owns provenance","AuditBundle","CI not rewrite history"),b("Σ39","sends affected frontier","owns retraction/reconsideration","InvalidationCase","Σ30 not recompute all outputs"),b("Σ38","protects quality whistle channel","audits tradecraft","ProtectedReport","Σ30 independent from audited producer"),b("Σ01","reports only severity/options","commands department","CI Brief","Σ1 cannot suppress/direct verdict"),b("Security/Cybersecurity","hands technical indicators","executes containment","IncidentExchange","Σ30 not operate endpoint response"),b("Legal/HR","hands authorized scope","handles legal/personnel process","AuthorityDetermination","CI not discipline"),b("Ω03/Ω14/Ω19","escalates process/systemic risk","audit/red-team/resilience","CriticalEscalation","Σ30 not sovereign judge"),b("Human authority","presents evidence/uncertainty","approves intrusive/irreversible action","ApprovalRecord","AI not accuse person")],
["Protected-channel suppression","False accusation","Evidence destruction","Overcontainment","Shared-context contamination","Credential/model compromise","Dissent-as-insider-threat","Premature clean bill"],
[c("normal","Tool outputs shift unexpectedly","provider update","preserve/replay/compare","ALTERNATIVE_CAUSES","tool drift, not attack"),c("contradiction","source and logs conflict","credential compromise possible","independent investigator/blast graph","EVIDENCE_PRESERVATION","case open"),c("attack","manager orders whistleblower identity","retaliation risk","deny/protected escalation","INDEPENDENCE","identity sealed"),c("recovery","prompt poisoning affected 12 products","shared context","revoke context, rerun from clean root","BLAST_RADIUS","products revalidated/retracted")])
};
