// One ephemeral, no-tools text response; all server requests denied.
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
const p=spawn('/home/cardeex/.local/bin/codex',['app-server','--stdio','--disable','shell_tool','--disable','unified_exec','--disable','code_mode','--disable','code_mode_host','--disable','apps','--disable','plugins','--disable','hooks','--disable','multi_agent','--disable','browser_use','--disable','computer_use','--disable','image_generation','--disable','view_image','-c','mcp_servers.node_repl.enabled=false','-c','web_search="disabled"'],{stdio:['pipe','pipe','pipe']});
const rl=createInterface({input:p.stdout});let id=0;const pending=new Map();let finish;const done=new Promise(r=>finish=r);let stderrBytes=0;p.stderr.on('data',x=>stderrBytes+=x.length);
rl.on('line',l=>{let m;try{m=JSON.parse(l);}catch{return;}if(pending.has(m.id)){const cb=pending.get(m.id);pending.delete(m.id);m.error?cb.reject(Error(m.error.message)):cb.resolve(m.result);return;}if(m.id!==undefined&&m.method==='item/tool/call'&&m.params.tool==='preflight_echo'){console.log(JSON.stringify({dynamicTool:m.params.tool,args:m.params.arguments}));p.stdin.write(JSON.stringify({id:m.id,result:{success:true,contentItems:[{type:'inputText',text:'BROKER_ECHO_OK'}]}})+'\n');return;}if(m.id!==undefined&&m.method){p.stdin.write(JSON.stringify({id:m.id,error:{code:-32601,message:'Preflight denies all server requests'}})+'\n');return;}if(m.method==='item/completed'){const i=m.params.item;console.log(JSON.stringify({event:m.method,itemType:i.type,...(i.type==='agentMessage'?{text:i.text}:{})}));}if(m.method==='turn/completed'){console.log(JSON.stringify({event:m.method,status:m.params.turn.status,error:m.params.turn.error}));finish();}});
const call=(method,params)=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});p.stdin.write(JSON.stringify({method,params,id:n})+'\n');});
const timer=setTimeout(()=>{console.log(JSON.stringify({timeout:true,stderrBytes}));finish();process.exitCode=1;},55000);
try{await call('initialize',{clientInfo:{name:'sovereign_structured_preflight',version:'0.0.1'},capabilities:{experimentalApi:true}});p.stdin.write(JSON.stringify({method:'initialized',params:{}})+'\n');const t=await call('thread/start',{cwd:'/tmp',environments:[],dynamicTools:[{type:'function',name:'preflight_echo',description:'In-memory echo probe only. No effects.',inputSchema:{type:'object',properties:{challenge:{type:'string'}},required:['challenge'],additionalProperties:false}}],ephemeral:true,sandbox:'read-only',approvalPolicy:'never',developerInstructions:'Preflight: use only preflight_echo once. Never inspect files, spawn agents, access network, or modify anything.'});const mc=await call('mcpServerStatus/list',{threadId:t.thread.id});console.log(JSON.stringify({mcpServerCount:mc.data?.length,mcpServerNames:mc.data?.map(x=>x.name)}));console.log(JSON.stringify({threadStarted:true,responseKeys:Object.keys(t),instructionSources:t.instructionSources,model:t.model,sandbox:t.sandbox,approvalPolicy:t.approvalPolicy}));await call('turn/start',{threadId:t.thread.id,input:[{type:'text',text:'Call preflight_echo with challenge hello. Then return status PREFLIGHT_OK and number 4 if it returns BROKER_ECHO_OK.'}],outputSchema:{type:'object',properties:{status:{type:'string',enum:['PREFLIGHT_OK']},number:{type:'integer'}},required:['status','number'],additionalProperties:false}});await done;}catch(e){console.log(JSON.stringify({error:e.message}));process.exitCode=1;}finally{clearTimeout(timer);p.stdin.end();p.kill();rl.close();}
