import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';
import {FactoryEngine} from '../../factory/lib/engine.mjs';
import {ownerProcessIsAlive} from '../../factory/lib/process-identity.mjs';
import {missionInferenceBudget} from '../../factory/lib/mission-inference-budget.mjs';
import {methodRecoveryPolicy} from '../../factory/lib/method-recovery.mjs';
import {missionReport,formatMissionReport} from '../../factory/lib/report.mjs';
import {dependencyGates} from '../../factory/lib/dependency-gates.mjs';
import {auditRouteLineage} from '../../reconstruction/verification/full-route-audit.mjs';
import {methodRecoveryFixtureProvider} from './fixtures/method-recovery-model.mjs';
for(const value of [null,{}, {mode:'arbitrary',maxRounds:1},{mode:'reviewed-method-v1',maxRounds:0},{mode:'reviewed-method-v1',maxRounds:101},
  {mode:'reviewed-method-v1',maxRounds:1.5},{mode:'reviewed-method-v1',maxRounds:'2'},{mode:'reviewed-method-v1',maxRounds:1,reset:true}])
  test('Method recovery rejects an invalid explicit policy '+JSON.stringify(value),()=>assert.throws(()=>methodRecoveryPolicy(value)));
test('Method recovery policy copies the explicit finite authorization',()=>{const input={mode:'reviewed-method-v1',maxRounds:2},policy=methodRecoveryPolicy(input);
  assert.deepEqual(policy,input);assert.notEqual(policy,input);});
for(const boundary of ['before-origin','after-origin','after-review','before-completion','after-completion'])test('REAL SIGKILL, SIMULATED method recovery: '+boundary,async t=>{
  const directory=fs.mkdtempSync(join(tmpdir(),'method-recovery-kill-'));let engine;
  t.after(()=>{engine?.close();fs.rmSync(directory,{recursive:true,force:true});});
  const child=spawnSync(process.execPath,[new URL('./fixtures/method-recovery-process.mjs',import.meta.url).pathname,directory,boundary],{encoding:'utf8',timeout:30000});
  assert.equal(child.signal,'SIGKILL',child.stderr+child.stdout);assert.equal(child.status,null);
  const fixture=JSON.parse(fs.readFileSync(join(directory,'fixture.json'),'utf8'));assert.equal(ownerProcessIsAlive({processIdentity:fixture.owner,pid:fixture.owner.pid}),false);
  engine=new FactoryEngine({databasePath:join(directory,'state.sqlite'),workspaceRoot:join(directory,'workspaces')});
  const originalPolicy=engine.status(fixture.missionId).mission.policy;
  let calls=0;const factory=methodRecoveryFixtureProvider('sim-parent');
  engine.workers.providerFactory=()=>{const provider=factory(),generate=provider.generate.bind(provider);provider.generate=async(...args)=>{calls++;return generate(...args);};return provider;};
  const result=await engine.run(fixture.missionId);assert.equal(result.mission.status,'COMPLETED',JSON.stringify(result.mission.pending));
  assert.equal(result.outcome.payload.body,'13');assert.deepEqual(result.mission.policy,originalPolicy);
  assert.equal(missionInferenceBudget(engine.registry,fixture.missionId).reserved,8);
  assert.equal(calls,['before-origin','after-origin'].includes(boundary)?4:2);
  assert.equal(engine.store.list('method-recovery-round').length,1);assert.equal(engine.store.list('method-recovery-completion').length,1);
  const deliveredNode=engine.store.get('node',`${fixture.missionId}:deliver`).data;
  assert.equal(deliveredNode.history.filter(h=>h.status==='RETURNED').length,1);
  const durableOutcome=engine.store.get('artifact',result.outcome.id).data;
  const gates=dependencyGates(engine.registry,result.outcome.id);
  assert.equal(gates.dependencies[0].acceptedBeforeFirstAttempt,false,'The new plan was NOT accepted before the old method; do not backdate it');
  assert.ok(gates.methodRevision.firstProducerSequence>gates.firstProducerSequence);
  assert.equal(gates.methodRevision.firstProducerRunId,durableOutcome.payload.producerRunId);
  assert.equal(gates.methodRevision.dependencies[0].acceptedBeforeFirstRevisionAttempt,true);
  const old=engine.store.list('method-recovery-round')[0].data.failures[0].artifact;
  const oldGates=dependencyGates(engine.registry,old.id);assert.equal(oldGates.methodRevision,undefined);
  assert.equal(oldGates.dependencies[0].acceptedBeforeFirstAttempt,true,'Original plan acceptance remains the original historical fact');
  assert.equal(auditRouteLineage(engine,fixture.missionId).length,2);
  const journal=engine.store.verifyJournal(),report=missionReport(engine.store,fixture.missionId,{registry:engine.registry});
  assert.equal(report.methodRecovery.reservedRounds,1);assert.equal(report.methodRecovery.remainingRounds,0);
  assert.equal(report.methodRecovery.rounds[0].status,'INSTALLED_HISTORICALLY');
  assert.equal(report.methodRecovery.rounds[0].failures,undefined,'Public recovery progress never discloses rejected diagnostic data');
  const installedPlanRef=engine.store.list('method-recovery-completion')[0].data.replacementPlan;
  assert.equal(engine.store.get(installedPlanRef.type,installedPlanRef.id,installedPlanRef.version).data.plan.nodes
    .find(node=>node.id==='deliver').method.id,'term-reconstruction');
  assert.match(formatMissionReport(report),/Diagnósticos, productos rechazados/);assert.deepEqual(engine.store.verifyJournal(),journal);
  const outcome=result.outcome.id,before=calls;engine.close();
  engine=new FactoryEngine({databasePath:join(directory,'state.sqlite'),workspaceRoot:join(directory,'workspaces')});
  engine.workers.providerFactory=()=>{throw Error('Completed reentry must not infer');};
  assert.equal((await engine.run(fixture.missionId)).outcome.id,outcome);assert.equal(calls,before);engine.store.verifyJournal();
  const completion=engine.store.list('method-recovery-completion')[0];
  engine.store.put('method-recovery-completion',completion.id,{...completion.data,forged:'Changed head is not the committed epoch'},{expectedVersion:completion.version});
  assert.throws(()=>dependencyGates(engine.registry,outcome),{code:'METHOD_RECOVERY_INTEGRITY'});
  assert.deepEqual(dependencyGates(engine.registry,old.id),oldGates,'A later altered revision cannot rewrite the old candidate history');
});
